const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {getFirestore,FieldPath,FieldValue}=require('firebase-admin/firestore');
const {getAuth}=require('firebase-admin/auth');
const {isNamedAdmin}=require('./broadcast_policy');
const opts={region:'europe-west1',timeoutSeconds:120,invoker:'public'};
function guard(r){if(!isNamedAdmin(r.auth))throw new HttpsError('permission-denied','Yönetici yetkisi gerekli.');return r.auth.uid;}
function clean(v){return String(v??'').trim();}
function norm(v){return clean(v).toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');}
const sources=['moderation_reports','reports','user_reports','trust_reports','review_reports','event_reports'];
function queryFor(db,source){return source==='trust_reports'?db.collectionGroup(source):source==='event_reports'?db.collectionGroup('reports'):db.collection(source);}
function report(doc,source){const d=doc.data();return {path:doc.ref.path,id:doc.id,source,status:d.status==='pending'?'open':d.status||'open',targetType:d.targetType||(source==='user_reports'?'user':source==='trust_reports'?'business':source==='event_reports'?'event':source==='review_reports'?'review':''),targetId:clean(d.targetId||d.reportedUserId||(source==='trust_reports'||source==='event_reports'?doc.ref.parent.parent?.id:'')),reason:clean(d.reason),details:clean(d.details),decisionReason:clean(d.decisionReason)};}
exports.adminModerationPage=onCall(opts,async r=>{guard(r);const db=getFirestore(),items=[];const status=clean(r.data?.status)||'open';let index=Number(r.data?.cursor?.index||0),after=clean(r.data?.cursor?.after);if(!Number.isInteger(index)||index<0||index>sources.length)throw new HttpsError('invalid-argument','Geçersiz sayfa.');
 while(index<sources.length&&items.length<40){const source=sources[index];let q=queryFor(db,source).orderBy(FieldPath.documentId()).limit(100);if(after)q=q.startAfter(after);const snap=await q.get();for(const doc of snap.docs){after=source==='trust_reports'||source==='event_reports'?doc.ref.path:doc.id;if(source==='event_reports'&&!doc.ref.path.startsWith('social_events/'))continue;const item=report(doc,source);if(status==='all'||item.status===status)items.push(item);if(items.length===40)return {items,cursor:{index,after}};}if(snap.size<100){index++;after='';}}
 return {items,cursor:index<sources.length?{index,after}:null};});
exports.adminDirectoryPage=onCall(opts,async r=>{guard(r);const kind=r.data?.kind;if(!['users','photo_spots'].includes(kind))throw new HttpsError('invalid-argument','Geçersiz liste.');const db=getFirestore(),items=[],search=norm(r.data?.search);let after=clean(r.data?.cursor);const status=clean(r.data?.status);
 while(items.length<40){let q=db.collection(kind).orderBy(FieldPath.documentId()).limit(150);if(after)q=q.startAfter(after);const snap=await q.get();for(const doc of snap.docs){after=doc.id;const d=doc.data();if(kind==='photo_spots'&&status&&d.status!==status)continue;const values=kind==='users'?[d.displayName,d.username,d.email,doc.id]:[d.name,d.city,d.district,d.category,doc.id];if(search&&!norm(values.join(' ')).includes(search))continue;items.push({id:doc.id,name:clean(d.displayName||d.name||d.username),username:clean(d.username),email:clean(d.email),city:clean(d.city),district:clean(d.district),category:clean(d.category),status:clean(d.status),banned:d.banned===true});if(items.length===40)return {items,cursor:after};}if(snap.size<150)return {items,cursor:null};}
 return {items,cursor:after};});
exports.adminReviewReport=onCall(opts,async r=>{const uid=guard(r),{path,action,reason}=r.data||{};if(typeof path!=='string'||!(/^(moderation_reports|reports|user_reports|review_reports)\/[^/]+$/.test(path)||/^business_venues\/[^/]+\/trust_reports\/[^/]+$/.test(path)||/^social_events\/[^/]+\/reports\/[^/]+$/.test(path)))throw new HttpsError('invalid-argument','Geçersiz şikâyet.');if(!['reviewing','dismissed','remove_post','disable_user','actioned'].includes(action)||clean(reason).length<3)throw new HttpsError('invalid-argument','İşlem ve en az üç karakterlik gerekçe gerekli.');const db=getFirestore(),ref=db.doc(path),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Şikâyet bulunamadı.');const d=snap.data();const type=d.targetType||(path.startsWith('user_reports/')?'user':'');const target=clean(d.targetId||d.reportedUserId);if(['remove_post','disable_user'].includes(action)&&(!target||target.includes('/')))throw new HttpsError('invalid-argument','Hedef bulunamadı.');
 if(action==='disable_user'){if(type!=='user'||target===uid)throw new HttpsError('failed-precondition','Bu hesaba yaptırım uygulanamaz.');const user=await getAuth().getUser(target);if(user.customClaims?.admin===true)throw new HttpsError('permission-denied','Yönetici hesabı kısıtlanamaz.');await getAuth().updateUser(target,{disabled:true});await getAuth().revokeRefreshTokens(target);}
 await db.runTransaction(async tx=>{const current=await tx.get(ref);if(!current.exists)throw new HttpsError('not-found','Şikâyet bulunamadı.');if(clean(current.data().targetId||current.data().reportedUserId)!==target)throw new HttpsError('aborted','Şikâyet değişti, yeniden dene.');let original=null,postRef;if(action==='remove_post'){if(type!=='post')throw new HttpsError('failed-precondition','Bu şikâyet bir gönderiye ait değil.');postRef=db.doc('posts/'+target);const post=await tx.get(postRef);original=post.data()||null;}
 const audit=db.collection('admin_audit_logs').doc();tx.create(audit,{adminUid:uid,action,reportPath:path,targetId:target,reason:clean(reason),original,createdAt:FieldValue.serverTimestamp()});if(postRef)tx.delete(postRef);if(action==='disable_user')tx.set(db.doc('users/'+target),{banned:true,disabled:true,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.update(ref,{status:action==='reviewing'?'reviewing':action==='dismissed'?'dismissed':'actioned',decisionReason:clean(reason),reviewedBy:uid,reviewedAt:FieldValue.serverTimestamp()});});return {ok:true};});
exports.adminGrowthSummary=onCall(opts,async r=>{guard(r);const db=getFirestore();const count=async q=>(await q.count().get()).data().count;const counts=await Promise.all([count(db.collection('users')),count(db.collection('posts')),count(db.collection('social_events')),count(db.collection('business_venues').where('verified','==',true)),count(db.collection('business_claims').where('status','==','pending_review'))]);let after=null;const cities={};while(true){let q=db.collection('users').orderBy(FieldPath.documentId()).select('city').limit(500);if(after)q=q.startAfter(after);const snap=await q.get();for(const doc of snap.docs){const city=clean(doc.data().city);if(city)cities[city]=(cities[city]||0)+1;}if(snap.size<500)break;after=snap.docs.at(-1);}return {counts,cities};});
