'use strict';
// Free business management; legacy paid endpoints remain as explicit retirement responses.
const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {getFirestore,FieldValue,Timestamp}=require('firebase-admin/firestore');
const {createHash,randomBytes}=require('crypto');
const callable=handler=>onCall({region:'europe-west1'},handler);
const stamp=()=>FieldValue.serverTimestamp();
const clean=(v,n=240)=>String(v??'').trim().slice(0,n);
function id(v){const x=clean(v);if(!x||x.includes('/'))throw new HttpsError('invalid-argument','Geçersiz kayıt kimliği.');return x;}
function auth(r){if(!r.auth?.uid)throw new HttpsError('unauthenticated','Giriş gerekli.');return r.auth.uid;}
function owns(uid,v,c){return(v.verified===true&&v.ownerUid===uid)||(c.status==='verified'&&c.applicantUid===uid);}
async function owner(r){const uid=auth(r),db=getFirestore(),key=id(r.data?.venueKey),base=db.collection('business_venues').doc(key);const [v,c]=await Promise.all([base.get(),db.collection('business_claims').doc(key).get()]);if(!owns(uid,v.data()||{},c.data()||{}))throw new HttpsError('permission-denied','Doğrulanmış işletme sahibi gerekli.');return{uid,db,key,base,venue:v.data()||{}};}
function hash(...parts){return createHash('sha256').update(parts.join('|')).digest('hex');}
function millis(v){return v?.toMillis?.()||0;}
function source(v){return ['tbt','instagram','whatsapp','creator','direct'].includes(v)?v:'direct';}
function localTime(ms){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Istanbul',weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return {day:{Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7}[p.weekday],clock:p.hour+':'+p.minute,date:p.year+'-'+p.month+'-'+p.day};}
function available(c,now=Date.now(),window=false){if(c.active===false||millis(c.startsAt)>now||millis(c.validUntil)<=now)return false;if(!window)return true;const local=localTime(now);return (!c.days?.length||c.days.includes(local.day))&&(!c.dailyStart||(local.clock>=c.dailyStart&&local.clock<c.dailyEnd));}
function campaignValues(d,now=Date.now()){
 const goal=clean(d.goal,20),title=clean(d.title,140),description=clean(d.description,700),terms=clean(d.terms,500),start=Number(d.startsAtMs),end=Number(d.validUntilMs),quota=Number(d.maxClaims??100);
 if(!['offer','reservation','event'].includes(goal)||title.length<3||!description||!Number.isFinite(start)||!Number.isFinite(end)||end<=Math.max(now,start)||end-start>366*864e5)throw new HttpsError('invalid-argument','Başlık, açıklama ve geçerli başlangıç/bitiş tarihleri gerekli.');
 if(goal==='event'&&start<=now)throw new HttpsError('invalid-argument','Etkinlik gelecekte başlamalı.');
 if(!Number.isInteger(quota)||quota<1||quota>100000)throw new HttpsError('invalid-argument','Kontenjan 1–100000 arasında olmalı.');
 const dailyStart=clean(d.dailyStart,5),dailyEnd=clean(d.dailyEnd,5),days=Array.isArray(d.days)?[...new Set(d.days)]:[];
 if(days.some(x=>!Number.isInteger(x)||x<1||x>7)||((dailyStart||dailyEnd)&&(!/^([01]\d|2[0-3]):[0-5]\d$/.test(dailyStart)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(dailyEnd)||dailyEnd<=dailyStart)))throw new HttpsError('invalid-argument','Günleri ve aynı gün içindeki saat aralığını kontrol et.');
 return{goal,title,description,terms,startsAt:Timestamp.fromMillis(start),validUntil:Timestamp.fromMillis(end),maxClaims:quota,dailyStart,dailyEnd,days};
}
function publicView(s){const d=s.data();return{id:s.id,venueKey:d.venueKey,venueName:d.venueName,city:d.city,address:d.address,category:d.category,venueId:d.venueId,goal:d.goal,title:d.title,description:d.description,terms:d.terms||'',startsAtMs:millis(d.startsAt),validUntilMs:millis(d.validUntil),dailyStart:d.dailyStart||'',dailyEnd:d.dailyEnd||'',days:d.days||[],maxClaims:d.maxClaims,couponId:d.couponId||'',socialEventId:d.socialEventId||'',active:d.active,availableNow:available(d,Date.now(),true)};}
exports.createBusinessGrowthCampaign=callable(async r=>{
 const {uid,db,key,base,venue}=await owner(r),d=r.data||{},values=campaignValues(d),requestId=id(d.requestId),campaignId=hash(key,uid,requestId),ref=db.collection('business_growth_campaigns').doc(campaignId),goal=values.goal,split=key.indexOf(':'),category=key.slice(0,split),venueId=key.slice(split+1),publicDescription=[values.description,values.terms&&'Koşullar: '+values.terms,values.dailyStart&&`Saatler: ${values.dailyStart}–${values.dailyEnd}`,values.days.length&&'Günler: '+values.days.map(x=>['','Pzt','Sal','Çar','Per','Cum','Cmt','Paz'][x]).join(', ')].filter(Boolean).join('\n');
 return db.runTransaction(async tx=>{const existing=await tx.get(ref);if(existing.exists)return{id:ref.id};const current=await tx.get(base);if(current.data()?.verified!==true||current.data()?.ownerUid!==uid)throw new HttpsError('permission-denied','İşletme yetkisi değişti.');
 const venueName=clean(venue.venueName||venue.name,160),common={...values,venueKey:key,venueName,city:clean(venue.city,80),address:clean(venue.address,300),category,venueId,active:true,ownerUid:uid,createdBy:uid,createdAt:stamp(),updatedAt:stamp(),views:0,opens:0,sources:{},version:1};
 if(goal==='offer'){common.couponId=campaignId;tx.set(base.collection('coupons').doc(campaignId),{...values,description:publicDescription,growthCampaignId:campaignId,claimCount:0,useCount:0,active:true,createdBy:uid,createdAt:stamp(),updatedAt:stamp()});tx.set(base.collection('campaigns').doc(campaignId),{...values,description:publicDescription,growthCampaignId:campaignId,couponId:campaignId,active:true,createdBy:uid,createdAt:stamp(),updatedAt:stamp()});}
 if(goal==='event'){common.socialEventId='business_'+campaignId;tx.set(base.collection('program').doc(campaignId),{title:values.title,description:publicDescription,startsAt:values.startsAt,endsAt:values.validUntil,growthCampaignId:campaignId,socialEventId:common.socialEventId,active:true,createdBy:uid,createdAt:stamp(),updatedAt:stamp()});tx.set(db.collection('social_events').doc(common.socialEventId),{id:common.socialEventId,title:values.title,description:publicDescription,startsAt:values.startsAt,endsAt:values.validUntil,type:'other',customTypeLabel:'İşletme etkinliği',hostId:uid,hostName:venueName,capacity:values.maxClaims,participantIds:[],city:common.city,locationLabel:venueName,address:common.address,latitude:venue.latitude??null,longitude:venue.longitude??null,status:'open',visibility:'public',allowedUserIds:[],accessType:'free',ticketPriceMinor:0,currency:'TRY',paymentStatus:'notRequired',trustStatus:'verified_business',salesStatus:'not_required',riskLevel:'low',paymentReleaseStatus:'not_applicable',source:'business_program',businessVenueKey:key,businessVenueName:venueName,businessProgramId:campaignId,verifiedBusiness:true,createdAt:stamp(),updatedAt:stamp()});}
 tx.set(ref,common);return{id:ref.id};});
});
exports.setBusinessGrowthCampaignActive=callable(async r=>{const {uid,db,key,base}=await owner(r),ref=db.collection('business_growth_campaigns').doc(id(r.data?.campaignId)),active=r.data?.active===true;await db.runTransaction(async tx=>{const snap=await tx.get(ref),c=snap.data();if(!c||c.venueKey!==key||c.ownerUid!==uid)throw new HttpsError('permission-denied','Kampanya bu işletmeye ait değil.');if(active&&millis(c.validUntil)<=Date.now())throw new HttpsError('failed-precondition','Süresi dolan kampanya yeniden açılamaz.');tx.update(ref,{active,updatedAt:stamp()});if(c.goal==='offer'){tx.update(base.collection('coupons').doc(ref.id),{active,updatedAt:stamp()});tx.update(base.collection('campaigns').doc(ref.id),{active,updatedAt:stamp()});}if(c.goal==='event'){tx.update(base.collection('program').doc(ref.id),{active,updatedAt:stamp()});tx.update(db.collection('social_events').doc(c.socialEventId),{status:active?'open':'cancelled',updatedAt:stamp()});}});return{ok:true};});
exports.listBusinessGrowthOffers=callable(async r=>{const city=clean(r.data?.city,80);if(!city)return{items:[]};const db=getFirestore(),snap=await db.collection('business_growth_campaigns').where('city','==',city).limit(100).get(),items=[];const candidates=snap.docs.filter(s=>s.data().active!==false&&millis(s.data().validUntil)>Date.now());const venues=new Map();await Promise.all([...new Set(candidates.map(s=>s.data().venueKey))].map(async key=>venues.set(key,(await db.collection('business_venues').doc(key).get()).data())));for(const s of candidates){const c=s.data(),v=venues.get(c.venueKey);if(v?.verified===true&&v.ownerUid===c.ownerUid)items.push(publicView(s));}return{items:items.sort((a,b)=>a.validUntilMs-b.validUntilMs).slice(0,30)};});
exports.getBusinessGrowthOffer=callable(async r=>{const db=getFirestore(),snap=await db.collection('business_growth_campaigns').doc(id(r.data?.campaignId)).get();if(!snap.exists)throw new HttpsError('not-found','Fırsat bulunamadı.');const c=snap.data(),v=(await db.collection('business_venues').doc(c.venueKey).get()).data();if(!v?.verified||v.ownerUid!==c.ownerUid)throw new HttpsError('not-found','İşletme yayında değil.');return{item:publicView(snap)};});
exports.recordBusinessGrowthMetric=callable(async r=>{const uid=auth(r),d=r.data||{},metric=d.metric;if(!['view','open'].includes(metric))throw new HttpsError('invalid-argument','Geçersiz ölçüm.');const db=getFirestore(),ref=db.collection('business_growth_campaigns').doc(id(d.campaignId)),day=localTime(Date.now()).date,dedupe=ref.collection('metric_events').doc(hash(uid,day,metric)),origin=source(d.source);await db.runTransaction(async tx=>{const [c,e]=await Promise.all([tx.get(ref),tx.get(dedupe)]);if(!c.exists||e.exists||c.data().ownerUid===uid||c.data().active===false||millis(c.data().validUntil)<=Date.now())return;const v=await tx.get(db.collection('business_venues').doc(c.data().venueKey));if(v.data()?.verified!==true||v.data()?.ownerUid!==c.data().ownerUid)return;tx.set(dedupe,{createdAt:stamp(),source:origin});tx.update(ref,{[metric==='view'?'views':'opens']:FieldValue.increment(1),['sources.'+origin+'.'+metric]:FieldValue.increment(1)});});return{ok:true};});
exports.getBusinessGrowthDashboard=callable(async r=>{const {db,key,base}=await owner(r),snap=await db.collection('business_growth_campaigns').where('venueKey','==',key).limit(100).get();const items=await Promise.all(snap.docs.map(async s=>{const c=s.data(),out={...publicView(s),views:Number(c.views||0),opens:Number(c.opens||0),sources:c.sources||{},claims:0,uses:0,participants:0};if(c.couponId){const coupon=(await base.collection('coupons').doc(c.couponId).get()).data()||{};out.claims=Number(coupon.claimCount||0);out.uses=Number(coupon.useCount||0);}if(c.socialEventId){const event=(await db.collection('social_events').doc(c.socialEventId).get()).data()||{};out.participants=Array.isArray(event.participantIds)?event.participantIds.length:0;}return out;}));return{items:items.sort((a,b)=>b.validUntilMs-a.validUntilMs),model:'free',measurementVersion:1};});
// Claim and redemption are both atomic. Existing wallet document IDs remain unchanged.
exports.claimBusinessCoupon=callable(async r=>{const uid=auth(r),key=id(r.data?.venueKey),couponId=id(r.data?.couponId),db=getFirestore(),base=db.collection('business_venues').doc(key),couponRef=base.collection('coupons').doc(couponId),claimRef=base.collection('coupon_claims').doc(couponId+'_'+uid);const data=await db.runTransaction(async tx=>{const [venue,coupon,existing]=await Promise.all([tx.get(base),tx.get(couponRef),tx.get(claimRef)]);const c=coupon.data();if(venue.data()?.verified!==true||!c)throw new HttpsError('not-found','Kupon bulunamadı.');if(venue.data().ownerUid===uid)throw new HttpsError('failed-precondition','Kendi işletmenin kuponunu alamazsın.');if(!available(c,Date.now()))throw new HttpsError('failed-precondition','Kupon şu anda alınamıyor.');if(existing.exists)return existing.data();if(Number(c.claimCount||0)>=Number(c.maxClaims||0))throw new HttpsError('resource-exhausted','Kupon kontenjanı doldu.');const result={token:'TBT-'+randomBytes(12).toString('hex').toUpperCase(),couponId,venueKey:key,userUid:uid,status:'ready',title:clean(c.title,160),validUntil:c.validUntil,source:source(r.data?.source),createdAt:stamp(),updatedAt:stamp()};tx.set(claimRef,result);tx.set(db.collection('users').doc(uid).collection('business_coupons').doc(key+'_'+couponId),result);tx.update(couponRef,{claimCount:FieldValue.increment(1),updatedAt:stamp()});return result;});return{...data,validUntilMs:millis(data.validUntil)};});
exports.validateBusinessCoupon=callable(async r=>{const {uid,db,base}=await owner(r),token=clean(r.data?.token,120).toUpperCase(),found=await base.collection('coupon_claims').where('token','==',token).limit(1).get();if(found.empty)throw new HttpsError('not-found','Kupon bulunamadı.');return db.runTransaction(async tx=>{const claim=await tx.get(found.docs[0].ref),d=claim.data()||{},couponRef=base.collection('coupons').doc(id(d.couponId)),coupon=await tx.get(couponRef);if(d.status!=='ready'||millis(d.validUntil)<=Date.now())throw new HttpsError('failed-precondition','Kupon kullanılmış veya süresi dolmuş.');if(!coupon.exists||!available(coupon.data(),Date.now(),true))throw new HttpsError('failed-precondition','Kupon geçerli gün/saat dışında veya duraklatılmış.');tx.update(claim.ref,{status:'used',usedAt:stamp(),validatedBy:uid,updatedAt:stamp()});tx.update(couponRef,{useCount:FieldValue.increment(1),updatedAt:stamp()});tx.set(db.collection('users').doc(d.userUid).collection('business_coupons').doc(d.venueKey+'_'+d.couponId),{status:'used',usedAt:stamp(),updatedAt:stamp()},{merge:true});return{ok:true,title:d.title};});});
exports.recordBusinessMetric=callable(async r=>{const uid=auth(r),key=id(r.data?.venueKey),metric=clean(r.data?.metric,40);if(!['profile_view','directions','phone','menu_view','campaign_view','campaign_save','event_view','reservation_open'].includes(metric))throw new HttpsError('invalid-argument','Geçersiz ölçüm.');const db=getFirestore(),base=db.collection('business_venues').doc(key),day=localTime(Date.now()).date,event=base.collection('metric_events').doc(hash(uid,day,metric));await db.runTransaction(async tx=>{const [venue,previous]=await Promise.all([tx.get(base),tx.get(event)]);if(previous.exists||venue.data()?.verified!==true||venue.data()?.ownerUid===uid)return;tx.set(event,{createdAt:stamp()});tx.set(base.collection('metrics').doc(metric),{count:FieldValue.increment(1),updatedAt:stamp()},{merge:true});tx.set(base.collection('metric_days').doc(day),{[metric]:FieldValue.increment(1),total:FieldValue.increment(1),updatedAt:stamp()},{merge:true});});return{ok:true};});
exports.getBusinessEntitlement=callable(async r=>{await owner(r);return{exists:true,verified:true,entitled:true,proEntitled:true,premiumEntitled:false,plan:'business_free',source:'free',billingRequired:false};});
exports.getBusinessPublicFeatures=callable(async r=>{const db=getFirestore(),snap=await db.collection('business_venues').doc(id(r.data?.venueKey)).get(),verified=snap.data()?.verified===true;return{verified,reservationsEnabled:verified,premiumActive:false,businessModel:'free'};});
const retired=callable(async r=>{auth(r);throw new HttpsError('failed-precondition','Boost ve Premium kaldırıldı. İşletme araçları ücretsiz; Müşteri kazan bölümünü kullan.');});
exports.startBusinessPremiumTrial=retired;
exports.createBusinessBoost=retired;
exports.adminSetBusinessPremium=retired;
