const {onCall, HttpsError} = require('firebase-functions/v2/https');
const {getFirestore, FieldValue, Timestamp} = require('firebase-admin/firestore');

function auth(request) { if (!request.auth?.uid) throw new HttpsError('unauthenticated','Giriş gerekli.'); return request.auth.uid; }
function clean(v,n=200){return String(v||'').trim().slice(0,n)}
function key(c,v){return `${clean(c,40)}:${clean(v,180)}`}
async function owner(request, venueKey){const uid=auth(request),db=getFirestore(),s=await db.collection('business_claims').doc(venueKey).get(),d=s.data()||{};if(d.status!=='verified'||d.applicantUid!==uid)throw new HttpsError('permission-denied','Doğrulanmış işletme sahibi gerekli.');return{uid,db}}

exports.followBusiness = onCall({region:'europe-west1'}, async request=>{const uid=auth(request),venueKey=clean(request.data?.venueKey,240),follow=request.data?.follow!==false;if(!venueKey)throw new HttpsError('invalid-argument','İşletme gerekli.');const db=getFirestore(),ref=db.collection('business_venues').doc(venueKey).collection('followers').doc(uid);if(follow)await ref.set({uid,createdAt:FieldValue.serverTimestamp()});else await ref.delete();return{following:follow};});

exports.recordBusinessMetric = onCall({region:'europe-west1'}, async request=>{auth(request);const venueKey=clean(request.data?.venueKey,240),metric=clean(request.data?.metric,40);const allowed=new Set(['profile_view','directions','phone','menu_view','campaign_view','campaign_save','event_view','reservation_open']);if(!venueKey||!allowed.has(metric))throw new HttpsError('invalid-argument','Geçersiz istatistik.');await getFirestore().collection('business_venues').doc(venueKey).collection('metrics').doc(metric).set({count:FieldValue.increment(1),updatedAt:FieldValue.serverTimestamp()},{merge:true});return{ok:true};});

exports.getBusinessDashboard = onCall({region:'europe-west1'}, async request=>{const venueKey=clean(request.data?.venueKey,240),{db}=await owner(request,venueKey);const [metrics,followers]=await Promise.all([db.collection('business_venues').doc(venueKey).collection('metrics').get(),db.collection('business_venues').doc(venueKey).collection('followers').count().get()]);const out={};metrics.docs.forEach(d=>out[d.id]=Number(d.data().count||0));return{metrics:out,followers:followers.data().count};});

exports.requestBusinessReservation = onCall({region:'europe-west1'}, async request=>{const uid=auth(request),venueKey=clean(request.data?.venueKey,240),partySize=Number(request.data?.partySize||0),atMs=Number(request.data?.atMs||0),note=clean(request.data?.note,500);if(!venueKey||!Number.isInteger(partySize)||partySize<1||partySize>50||atMs<Date.now())throw new HttpsError('invalid-argument','Rezervasyon bilgileri geçersiz.');const db=getFirestore(),ref=await db.collection('business_venues').doc(venueKey).collection('reservations').add({userUid:uid,partySize,at:Timestamp.fromMillis(atMs),note,status:'pending',createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return{id:ref.id,status:'pending'};});

exports.respondBusinessReservation = onCall({region:'europe-west1'}, async request=>{const venueKey=clean(request.data?.venueKey,240),reservationId=clean(request.data?.reservationId,180),decision=clean(request.data?.decision,20),{db}=await owner(request,venueKey);if(!['accepted','rejected'].includes(decision))throw new HttpsError('invalid-argument','Geçersiz karar.');await db.collection('business_venues').doc(venueKey).collection('reservations').doc(reservationId).update({status:decision,updatedAt:FieldValue.serverTimestamp()});return{status:decision};});

exports.createBusinessBoost = onCall({region:'europe-west1'}, async request=>{const venueKey=clean(request.data?.venueKey,240),targetType=clean(request.data?.targetType,30),targetId=clean(request.data?.targetId,180),days=Math.min(30,Math.max(1,Number(request.data?.days||3))),{uid,db}=await owner(request,venueKey);const until=Timestamp.fromMillis(Date.now()+days*86400000);await db.collection('business_venues').doc(venueKey).collection('boosts').add({targetType,targetId,days,status:'trial',billingStatus:'free_launch',startsAt:FieldValue.serverTimestamp(),endsAt:until,createdBy:uid});return{status:'trial',endsAtMs:until.toMillis()};});
