const fs=require('node:fs');
const {GoogleAuth}=require('../functions/node_modules/google-auth-library');
(async()=>{
 const auth=new GoogleAuth({scopes:['https://www.googleapis.com/auth/cloud-platform']});
 const client=await auth.getClient();
 const base='https://firebaserules.googleapis.com/v1/';
 const release=(await client.request({url:base+'projects/en-iyi-cekim-noktasi/releases/cloud.firestore'})).data;
 const set=(await client.request({url:base+release.rulesetName})).data;
 const file=set.source.files.find(f=>f.content.includes('match /proposals/{proposalId}'));
 if(!file)throw Error('Live proposal rules not found');
 const start=file.content.indexOf('match /proposals/{proposalId}');
 const end=file.content.indexOf('match /live_states/',start);
 if(end<0)throw Error('Unexpected live rules structure');
 const section=file.content.slice(start,end);
 const old='allow delete: if signedIn() && resource.data.authorId == request.auth.uid;';
 const replacement=`allow delete: if signedIn() && (resource.data.authorId == request.auth.uid || get(/databases/$(database)/documents/travel_plans/$(planId)).data.ownerId == request.auth.uid);`;
 if(!section.includes(old)&&!section.includes(replacement))throw Error('Live proposal delete rule changed; review required');
 const updated=file.content.slice(0,start)+section.replace(old,replacement)+file.content.slice(end);
 fs.writeFileSync('firestore.rules',updated);
 console.log('Prepared owner proposal deletion on current live rules; all other rules preserved');
})().catch(e=>{console.error(e.message);process.exitCode=1;});
