const assert = require('node:assert/strict');
if (!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST || '')) throw Error('Local emulator required');
const req = require('node:module').createRequire(require('node:path').resolve(__dirname, '../functions/package.json'));
const {initializeApp} = req('firebase-admin/app');
const {getFirestore, Timestamp} = req('firebase-admin/firestore');
initializeApp({projectId: 'demo-tbt'});
const db = getFirestore();
const {_chatActionHandler: action} = require('../functions/chat_collaboration');
const call = (uid, actionName, data = {}) => action({auth: {uid, token: {name: uid}}, data: {action: actionName, ...data}}, db);
(async () => {
  const {threadId} = await call('owner', 'create', {name: 'Test gezisi'});
  const args = {threadId}, ref = db.doc(`chat_threads/${threadId}`);
  await assert.rejects(call('outsider', 'rename', {...args, name: 'Hijack'}));
  const invite = await call('owner', 'invite', args);
  await call('member', 'join', invite);
  await call('member', 'join', invite);
  assert.equal((await ref.get()).data().memberIds.length, 2, 'join is idempotent');
  await assert.rejects(call('member', 'admin', {...args, userId: 'member'}));
  await assert.rejects(call('member', 'remove', {...args, userId: 'owner'}));
  await call('owner', 'invite', args);
  await assert.rejects(call('other', 'join', invite), 'rotated invite is revoked');
  await call('member', 'poll', {...args, question: 'Hangi gün?', options: ['Cumartesi','Pazar']});
  const poll = (await ref.collection('messages').get()).docs[0];
  await call('member', 'vote', {...args, messageId: poll.id, option: 0});
  await call('member', 'vote', {...args, messageId: poll.id, option: 1});
  assert.deepEqual((await poll.ref.get()).data().votes, {member: 1});
  await assert.rejects(call('outsider', 'vote', {...args, messageId: poll.id, option: 0}));
  await assert.rejects(call('owner', 'vote', {...args, messageId: poll.id, option: 9}));
  await call('member', 'closePoll', {...args, messageId: poll.id});
  await assert.rejects(call('owner', 'vote', {...args, messageId: poll.id, option: 0}));
  const msg = ref.collection('messages').doc('text');
  await msg.set({senderId:'member',type:'text',text:'Original',deleted:false,createdAt:Timestamp.now()});
  await assert.rejects(call('owner','edit',{...args,messageId:msg.id,text:'Forged'}));
  await assert.rejects(call('owner','delete',{...args,messageId:msg.id}));
  await call('member','edit',{...args,messageId:msg.id,text:'Edited'});
  assert.equal((await msg.get()).data().text,'Edited');
  await call('owner','pin',{...args,messageId:msg.id});
  await call('member','delete',{...args,messageId:msg.id});
  assert.equal((await msg.get()).data().deleted,true);
  assert.equal((await ref.get()).data().pinnedMessageId,undefined);
  await call('member','preferences',{...args,muted:true,readReceipts:false});
  assert.equal((await db.doc(`users/member/chat_preferences/${threadId}`).get()).data().muted,true);
  await call('owner','remove',{...args,userId:'member'});
  await assert.rejects(call('member','poll',{...args,question:'No',options:['A','B']}));
  const freshInvite = await call('owner','invite',args);
  await assert.rejects(call('member','join',freshInvite));
  // Real rules: even a current member cannot modify group membership or forge a poll.
  const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url'), now=Math.floor(Date.now()/1000);
  const token=uid=>`${encode({alg:'none',typ:'JWT'})}.${encode({iss:'https://securetoken.google.com/demo-tbt',aud:'demo-tbt',sub:uid,user_id:uid,iat:now,exp:now+3600,firebase:{sign_in_provider:'custom'}})}.`;
  const base=`http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/demo-tbt/databases/(default)/documents/chat_threads/${threadId}`;
  assert.equal((await fetch(base,{headers:{Authorization:`Bearer ${token('member')}`}})).status,403);
  assert.equal((await fetch(base,{headers:{Authorization:`Bearer ${token('owner')}`}})).status,200);
  assert.equal((await fetch(`${base}?updateMask.fieldPaths=memberIds`,{method:'PATCH',headers:{Authorization:`Bearer ${token('owner')}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{memberIds:{arrayValue:{values:[{stringValue:'owner'},{stringValue:'outsider'}]}}}})})).status,403);
  console.log('Chat tests passed: membership, invite rotation, role escalation, sender ownership, pin deletion, voting, preferences and access revocation.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.terminate());
