const assert=require('node:assert/strict');
const {initializeApp}=require('../functions/node_modules/firebase-admin/app');
const {getFirestore}=require('../functions/node_modules/firebase-admin/firestore');
const {getAuth}=require('../functions/node_modules/firebase-admin/auth');
initializeApp({projectId:'demo-tbt'});
const api=require('../functions/admin_operations');
const auth={uid:'admin',token:{admin:true,email_verified:true,email:'turgutburaktan@gmail.com'}};
const call=(name,data,identity=auth)=>api[name].run({auth:identity,data});
(async()=>{
 const db=getFirestore();
 await assert.rejects(call('adminDirectoryPage',{kind:'users'},{uid:'intruder',token:{}}),e=>e.code==='permission-denied');
 const batch=db.batch();for(let i=0;i<270;i++)batch.set(db.doc('users/user'+String(i).padStart(3,'0')),{displayName:i===269?'Işık Elazığ':'User '+i,city:'Elazığ'});await batch.commit();
 const match=await call('adminDirectoryPage',{kind:'users',search:'isik'});assert.equal(match.items.length,1);assert.equal(match.items[0].id,'user269');
 let cursor=null,seen=[];do{const page=await call('adminDirectoryPage',{kind:'users',cursor});seen.push(...page.items.map(x=>x.id));cursor=page.cursor;}while(cursor);assert.equal(new Set(seen).size,270);assert.equal(seen.length,270);
 for(const [path,data] of Object.entries({'reports/one':{targetType:'post',targetId:'post1',status:'open'},'user_reports/two':{reportedUserId:'victim',status:'pending'},'moderation_reports/three':{targetType:'post',targetId:'post2',status:'reviewing'},'business_venues/cafe/trust_reports/four':{status:'open'}}))await db.doc(path).set({...data,reason:'Test şikâyeti'});
 const reports=await call('adminModerationPage',{status:'open'});assert.equal(reports.items.length,3);
 await call('adminReviewReport',{path:'business_venues/cafe/trust_reports/four',action:'reviewing',reason:'İncelemeye alındı'});assert.equal((await call('adminModerationPage',{status:'reviewing'})).items.length,2);
 await assert.rejects(call('adminReviewReport',{path:'users/victim',action:'dismissed',reason:'Test'}),e=>e.code==='invalid-argument');
 await db.doc('posts/post1').set({caption:'test',userId:'victim'});await call('adminReviewReport',{path:'reports/one',action:'remove_post',reason:'Kural ihlali'});assert.equal((await db.doc('posts/post1').get()).exists,false);assert.equal((await db.doc('reports/one').get()).data().status,'actioned');assert.equal((await db.collection('admin_audit_logs').where('action','==','remove_post').get()).size,1);
 await getAuth().createUser({uid:'victim',email:'victim@example.test'});await db.doc('users/victim').set({displayName:'Victim'});await call('adminReviewReport',{path:'user_reports/two',action:'disable_user',reason:'Tekrarlanan ihlal'});assert.equal((await getAuth().getUser('victim')).disabled,true);assert.equal((await db.doc('users/victim').get()).data().banned,true);
 await db.doc('user_reports/self').set({reportedUserId:'admin',status:'pending'});await assert.rejects(call('adminReviewReport',{path:'user_reports/self',action:'disable_user',reason:'Test'}),e=>e.code==='failed-precondition');
 const growth=await call('adminGrowthSummary',{});assert.equal(growth.cities['Elazığ'],270);
 console.log('PASS admin: guarded access, full search, unique pagination, legacy reports, review tracking, audited removal, Auth restriction, admin protection, city totals');
})().catch(e=>{console.error(e);process.exitCode=1;});
