const assert = require('node:assert/strict');
if (!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST || '')) throw Error('Local emulator required');
const req = require('node:module').createRequire(require('node:path').resolve(__dirname, '../functions/package.json'));
const {initializeApp} = req('firebase-admin/app');
const {getFirestore, Timestamp} = req('firebase-admin/firestore');
initializeApp({projectId: 'demo-tbt'});
const db = getFirestore();
const {_chatActionHandler: action} = require('../functions/chat_collaboration');
const call = (uid, actionName, data = {}) => action({auth: {uid, token: {name: uid}}, data: {action: actionName, ...data}}, db);
(async () => {
  await db.doc('users/selected').set({displayName: 'Selected'});
  const picked = await call('picker', 'create', {name: 'Selected group', memberIds: ['selected', 'selected', 'picker']});
  assert.deepEqual((await db.doc(`chat_threads/${picked.threadId}`).get()).data().memberIds, ['picker', 'selected']);
  await assert.rejects(call('picker', 'create', {name: 'Missing user', memberIds: ['nonexistent']}));
  await assert.rejects(call('picker', 'create', {name: 'Invalid list', memberIds: 'selected'}));
  await assert.rejects(call('picker', 'create', {name: 'Too many', memberIds: Array(50).fill('selected')}));
  await db.doc('users/selected/blocked/picker').set({});
  await assert.rejects(call('picker', 'create', {name: 'Blocked', memberIds: ['selected']}));

  await db.doc('users/new-member').set({displayName: 'New member'});
  await db.doc('users/another-member').set({displayName: 'Another'});
  await assert.rejects(call('selected', 'addMembers', {threadId: picked.threadId, memberIds: ['new-member']}));
  await call('picker', 'addMembers', {threadId: picked.threadId, memberIds: ['new-member', 'new-member']});
  await call('picker', 'addMembers', {threadId: picked.threadId, memberIds: ['new-member']});
  assert.deepEqual((await db.doc(`chat_threads/${picked.threadId}`).get()).data().memberIds, ['picker', 'selected', 'new-member']);
  await db.doc('users/another-member/blocked/selected').set({});
  await assert.rejects(call('picker', 'addMembers', {threadId: picked.threadId, memberIds: ['another-member']}));
  await assert.rejects(call('picker', 'addMembers', {threadId: picked.threadId, memberIds: ['missing']}));
  await assert.rejects(call('picker', 'addMembers', {threadId: picked.threadId, memberIds: []}));
  await call('picker', 'remove', {threadId: picked.threadId, userId: 'new-member'});
  await call('picker', 'addMembers', {threadId: picked.threadId, memberIds: ['new-member']});
  assert.equal((await db.doc(`chat_threads/${picked.threadId}`).get()).data().removedIds.includes('new-member'), false);

  const {threadId} = await call('owner', 'create', {name: 'Test gezisi'});
  const args = {threadId}, ref = db.doc(`chat_threads/${threadId}`);
  await assert.rejects(call('outsider', 'rename', {...args, name: 'Hijack'}));
  const invite = await call('owner', 'invite', args);
  await call('member', 'join', invite);
  await call('member', 'join', invite);
  assert.equal((await ref.get()).data().memberIds.length, 2, 'join is idempotent');
  await assert.rejects(call('member', 'admin', {...args, userId: 'member'}));
  await assert.rejects(call('member', 'remove', {...args, userId: 'owner'}));
  await call('owner', 'invite', args);
  await assert.rejects(call('other', 'join', invite), 'rotated invite is revoked');
  await call('member', 'poll', {...args, question: 'Hangi gün?', options: ['Cumartesi','Pazar']});
  const poll = (await ref.collection('messages').get()).docs[0];
  await call('member', 'vote', {...args, messageId: poll.id, option: 0});
  await call('member', 'vote', {...args, messageId: poll.id, option: 1});
  assert.deepEqual((await poll.ref.get()).data().votes, {member: 1});
  await assert.rejects(call('outsider', 'vote', {...args, messageId: poll.id, option: 0}));
  await assert.rejects(call('owner', 'vote', {...args, messageId: poll.id, option: 9}));
  await call('member', 'closePoll', {...args, messageId: poll.id});
  await assert.rejects(call('owner', 'vote', {...args, messageId: poll.id, option: 0}));
  const msg = ref.collection('messages').doc('text');
  await msg.set({senderId:'member',type:'text',text:'Original',deleted:false,createdAt:Timestamp.now()});
  await assert.rejects(call('owner','edit',{...args,messageId:msg.id,text:'Forged'}));
  await assert.rejects(call('owner','delete',{...args,messageId:msg.id}));
  await call('member','edit',{...args,messageId:msg.id,text:'Edited'});
  assert.equal((await msg.get()).data().text,'Edited');
  await call('owner','pin',{...args,messageId:msg.id});
  await call('member','delete',{...args,messageId:msg.id});
  assert.equal((await msg.get()).data().deleted,true);
  assert.equal((await ref.get()).data().pinnedMessageId,undefined);
  await call('member','preferences',{...args,muted:true,readReceipts:false});
  assert.equal((await db.doc(`users/member/chat_preferences/${threadId}`).get()).data().muted,true);
  await call('owner','remove',{...args,userId:'member'});
  await assert.rejects(call('member','poll',{...args,question:'No',options:['A','B']}));
  const freshInvite = await call('owner','invite',args);
  await assert.rejects(call('member','join',freshInvite));
  // Real rules: even a current member cannot modify group membership or forge a poll.
  const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url'), now=Math.floor(Date.now()/1000);
  const token=uid=>`${encode({alg:'none',typ:'JWT'})}.${encode({iss:'https://securetoken.google.com/demo-tbt',aud:'demo-tbt',sub:uid,user_id:uid,iat:now,exp:now+3600,firebase:{sign_in_provider:'custom'}})}.`;
  const base=`http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/demo-tbt/databases/(default)/documents/chat_threads/${threadId}`;
  assert.equal((await fetch(base,{headers:{Authorization:`Bearer ${token('member')}`}})).status,403);
  assert.equal((await fetch(base,{headers:{Authorization:`Bearer ${token('owner')}`}})).status,200);
  assert.equal((await fetch(`${base}?updateMask.fieldPaths=memberIds`,{method:'PATCH',headers:{Authorization:`Bearer ${token('owner')}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{memberIds:{arrayValue:{values:[{stringValue:'owner'},{stringValue:'outsider'}]}}}})})).status,403);
  await db.doc('users/recipient').set({displayName: 'Recipient'});
  await db.doc('users/sender').set({displayName: 'Sender'});
  const dm = await call('sender', 'direct', {otherUserId: 'recipient'});
  const dmRef = db.doc(`chat_threads/${dm.threadId}`);
  assert.equal((await dmRef.get()).data().requestStatus, 'pending');
  await assert.rejects(call('sender', 'acceptRequest', dm));
  await assert.rejects(call('outsider', 'rejectRequest', dm));
  const dmUrl = base.replace(threadId, dm.threadId);
  assert.equal((await fetch(`${dmUrl}?updateMask.fieldPaths=requestStatus`, {method:'PATCH',headers:{Authorization:`Bearer ${token('sender')}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{requestStatus:{stringValue:'accepted'}}})})).status,403, 'sender cannot self-accept');
  const send = (who, kind) => fetch(`${dmUrl}/messages?documentId=${who}-${kind}`, {method:'POST',headers:{Authorization:`Bearer ${token(who)}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{senderId:{stringValue:who},text:{stringValue:'Hi'},type:{stringValue:kind},deleted:{booleanValue:false}}})});
  assert.equal((await send('sender','text')).status,200);
  assert.equal((await send('sender','image')).status,403,'media requires acceptance');
  assert.equal((await send('recipient','text')).status,403,'recipient must accept before replying');
  await call('recipient','acceptRequest',dm);
  assert.equal((await send('recipient','text')).status,200);
  await db.doc('users/second').set({displayName:'Second'});
  const declined=await call('sender','direct',{otherUserId:'second'});
  await call('second','rejectRequest',declined);
  assert.equal((await db.doc(`chat_threads/${declined.threadId}`).get()).data().requestStatus,'rejected');
  await call('sender','direct',{otherUserId:'second'});
  assert.equal((await db.doc(`chat_threads/${declined.threadId}`).get()).data().requestStatus,'rejected','opening again cannot reset refusal');
  await db.doc('users/known').set({displayName:'Known'});
  await db.doc('users/known/following/sender').set({userId:'sender'});
  const trusted=await call('sender','direct',{otherUserId:'known'});
  assert.equal((await db.doc(`chat_threads/${trusted.threadId}`).get()).data().requestStatus,'accepted');
  const legacyRef=db.doc('chat_threads/dm_legacy_sender');
  await db.doc('users/legacy').set({displayName:'Legacy'});
  await legacyRef.set({type:'direct',memberIds:['sender','legacy'],lastMessage:'Existing conversation'});
  await call('sender','direct',{otherUserId:'legacy'});
  assert.equal((await legacyRef.get()).data().requestStatus,undefined,'existing conversations remain unchanged');
  await db.doc('users/privacy').set({uid:'privacy',isOnline:true,lastSeenAt:Timestamp.now()});
  await call('privacy','messagePrivacy',{key:'showOnlineStatus',enabled:false});
  const privateProfile=(await db.doc('users/privacy').get()).data();
  assert.equal(privateProfile.isOnline,false);
  assert.equal(privateProfile.lastSeenAt,undefined);
  await call('privacy','messagePrivacy',{key:'showReadReceipts',enabled:false});
  assert.equal((await db.doc('users/privacy').get()).data().showOnlineStatus,false,'switches are independent');
  await assert.rejects(call('privacy','messagePrivacy',{key:'isAdmin',enabled:true}));
  const documents=base.substring(0,base.indexOf('/chat_threads/'));
  const patch=(url,who,fields)=>fetch(url,{method:'PATCH',headers:{Authorization:`Bearer ${token(who)}`,'Content-Type':'application/json'},body:JSON.stringify({fields})});
  assert.equal((await patch(`${documents}/users/privacy?updateMask.fieldPaths=isOnline`,'privacy',{isOnline:{booleanValue:true}})).status,403,'old client cannot reveal online state while disabled');
  assert.equal((await patch(`${documents}/users/privacy?updateMask.fieldPaths=lastSeenAt`,'privacy',{lastSeenAt:{timestampValue:new Date().toISOString()}})).status,403,'last seen remains hidden');
  await db.doc('chat_threads/privacy-test').set({type:'direct',memberIds:['privacy','recipient']});
  const receiptUrl=`${documents}/chat_threads/privacy-test?updateMask.fieldPaths=lastReadAt.privacy`;
  const receipt={lastReadAt:{mapValue:{fields:{privacy:{timestampValue:new Date().toISOString()}}}}};
  assert.equal((await patch(receiptUrl,'privacy',receipt)).status,403,'read receipt blocked server-side');
  await call('privacy','messagePrivacy',{key:'showReadReceipts',enabled:true});
  assert.equal((await patch(receiptUrl,'privacy',receipt)).status,200,'read receipt can resume after opt-in');
  await call('privacy','messagePrivacy',{key:'showOnlineStatus',enabled:true});
  assert.equal((await patch(`${documents}/users/privacy?updateMask.fieldPaths=isOnline`,'privacy',{isOnline:{booleanValue:true}})).status,200);
  console.log('Chat tests passed: membership, invite rotation, role escalation, sender ownership, pin deletion, voting, preferences and access revocation.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.terminate());

