if (!process.env.FIREBASE_AUTH_EMULATOR_HOST || !process.env.FIRESTORE_EMULATOR_HOST) throw Error('Refusing cloud access');
const sdk=require('node:module').createRequire(require('node:path').resolve(__dirname,'../functions/package.json'));
const assert=require('node:assert/strict');
const {initializeApp}=sdk('firebase-admin/app');
const {getFirestore}=sdk('firebase-admin/firestore');
const {getAuth}=sdk('firebase-admin/auth');
initializeApp({projectId:'demo-tbt'});
const api=require('../functions/photo_moderation');
const db=getFirestore(),auth=getAuth();
const files=new Map();
const bucket={file:path=>({getMetadata:async()=>{if(!files.has(path))throw Object.assign(Error('missing'),{code:404});return [structuredClone(files.get(path))];},
  setMetadata:async value=>files.set(path,structuredClone(value))})};
let scans=0;
const engine=api.createEngine({db,auth,bucket,scan:async path=>{scans++;if(path.includes('retry'))throw Error('vision_unavailable');return {adult:path.includes('mild')?'UNLIKELY':'VERY_LIKELY',racy:'LIKELY',medical:'UNLIKELY'};}});
const admin={uid:'administrator',token:{admin:true,email_verified:true,email:'turgutburaktan@gmail.com'}};
const user={uid:'alice',token:{}};
const invoke=(name,data,identity=admin)=>api[name].run({auth:identity,data});
async function post(id){const path=`users/alice/posts/${id}.jpg`,p={userId:'alice',mediaType:'image',storagePath:path,caption:'A test photo',imageUrl:`https://firebasestorage.googleapis.com/v0/b/en-iyi-cekim-noktasi.firebasestorage.app/o/${encodeURIComponent(path)}?alt=media&token=original`};files.set(path,{metadata:{firebaseStorageDownloadTokens:'original'}});await db.doc(`posts/${id}`).set(p);await engine.enqueue(id,p);return p;}
(async()=>{
  await auth.createUser({uid:'alice'});await db.doc('users/alice').set({displayName:'Alice'});
  await assert.rejects(invoke('reviewPhotoModeration',{id:'one',action:'confirm',reason:'test reason'},user),e=>e.code==='permission-denied');
  const p=await post('one');assert.equal((await db.doc('posts/one').get()).exists,true,'immediate publication');
  await Promise.all([engine.process('one'),engine.process('one')]);assert.equal(scans,1,'duplicate trigger uses lease');
  assert.equal((await db.doc('posts/one').get()).exists,false);
  assert.equal(files.get(p.storagePath).metadata.firebaseStorageDownloadTokens,null,'old public token revoked');
  assert.equal(files.get(p.storagePath).metadata.moderationBlocked,'true');
  assert.equal((await db.doc('photo_moderation/one').get()).data().status,'review');
  assert.equal((await db.doc('photo_moderation_accounts/alice').get()).data().strikes,undefined,'AI never counts strike');
  await engine.review('one','confirm','Explicit violation verified','administrator');
  await engine.review('one','confirm','Repeated admin click','administrator');
  assert.equal((await db.doc('photo_moderation_accounts/alice').get()).data().strikes,1);
  await assert.rejects(invoke('appealPhotoModeration',{id:'one',reason:'Incorrect detection'}, {uid:'bob',token:{}}),e=>e.code==='permission-denied');
  await invoke('appealPhotoModeration',{id:'one',reason:'Incorrect detection'},user);
  await assert.rejects(invoke('appealPhotoModeration',{id:'one',reason:'Duplicate appeal'},user));
  await engine.review('one','dismiss','Appeal accepted; no violation','administrator');
  assert.equal((await db.doc('photo_moderation_accounts/alice').get()).data().strikes,0);
  assert.equal((await db.doc('posts/one').get()).exists,true);
  assert.notEqual((await db.doc('posts/one').get()).data().imageUrl,p.imageUrl,'restore uses fresh token');
  await engine.enqueue('one',p);assert.equal((await db.doc('photo_moderation/one').get()).data().status,'dismissed');
  await post('mild');await engine.process('mild');assert.equal((await db.doc('posts/mild').get()).exists,true,'ambiguous remains visible');
  await post('retry');await engine.process('retry');const n=scans;await engine.process('retry');assert.equal(scans,n,'failed requests back off');
  assert.equal((await db.doc('posts/retry').get()).exists,true,'outage never quarantines publication');
  assert.equal((await db.doc('photo_moderation/retry').get()).data().workPending,true);
  for(let i=0;i<5;i++){const id=`violation${i}`;await post(id);await engine.process(id);await engine.review(id,'confirm','Verified distinct offending post','administrator');}
  let a=(await db.doc('photo_moderation_accounts/alice').get()).data();assert.equal(a.strikes,5);assert.equal(a.closureStatus,'pending');assert.equal((await auth.getUser('alice')).disabled,false,'fifth strike never auto disables');
  await engine.review('violation4','dismiss','Mistaken detection, strike reversed','administrator');
  await assert.rejects(engine.decideAccount('alice','approve','Stale fifth-strike approval','administrator'),e=>e.code==='failed-precondition');
  await engine.review('violation4','confirm','Reconfirmed with new evidence','administrator');
  await engine.decideAccount('alice','approve','Five confirmed explicit posts','administrator');
  assert.equal((await auth.getUser('alice')).disabled,true);
  assert.equal((await db.collection('posts').where('userId','==','alice').get()).empty,true);
  a=(await db.doc('photo_moderation_accounts/alice').get()).data();assert.equal(a.closureStatus,'closed');
  await assert.rejects(invoke('appealClosedPhotoAccount',{code:'0'.repeat(72),reason:'Please review'},null));
  await invoke('appealClosedPhotoAccount',{code:a.appealCode,reason:'Please review my closure'},null);
  await assert.rejects(invoke('appealClosedPhotoAccount',{code:a.appealCode,reason:'Replayed code'},null));
  assert.equal((await db.doc('photo_moderation_accounts/alice').get()).data().appealStatus,'pending');
  await engine.decideAccount('alice','reopen','Closure appeal accepted','administrator');
  assert.equal((await auth.getUser('alice')).disabled,false);
  assert.equal((await db.doc('posts/one').get()).exists,true);
  assert.equal((await db.doc('posts/violation0').get()).exists,false,'confirmed violation stays hidden after reopening');
  console.log('PASS photo moderation: immediate publication, scan leases, private media, retry/backoff, idempotent strikes, appeals, five-strike admin gate, stale approval denial, disable/restore');
})().catch(e=>{console.error(e);process.exitCode=1;});
