const assert = require('node:assert/strict');
if (!/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST || '')) throw Error('Local emulator required');
const req = require('node:module').createRequire(require('node:path').resolve(__dirname, '../functions/package.json'));
const {initializeApp} = req('firebase-admin/app');
const {getFirestore, Timestamp} = req('firebase-admin/firestore');
initializeApp({projectId:'demo-tbt'});
const db=getFirestore();
const {_publishing:publishing,_studio:studio}=require('../functions/social_publishing');
const call=(uid,action,postId='creator-post',data={})=>publishing({auth:uid?{uid}:null,data:{action,postId,...data}},db);
const center=(uid,action,data={})=>studio({auth:{uid},data:{action,...data}},db);
const reject=(promise,code)=>assert.rejects(promise,error=>error.code===code);
(async()=>{
  for(const uid of ['creator-owner','creator-reader','creator-other','creator-fake']) await db.doc(`users/${uid}`).set({uid,displayName:uid,isCreator:uid==='creator-owner'||uid==='creator-fake'});
  await db.doc('creator_invite_redemptions/creator-owner').set({uid:'creator-owner'});
  const original=db.doc('posts/creator-post');
  await original.set({userId:'creator-owner',mediaType:'image',caption:'Original',imageUrl:'https://example.com/image.jpg',createdAt:Timestamp.now()});
  await reject(call(null,'resolve'),'unauthenticated');
  await reject(call('creator-reader','repost','creator-post',{enabled:'true'}),'invalid-argument');
  await reject(call('creator-owner','repost','creator-post',{enabled:true}),'failed-precondition');
  await reject(call('creator-reader','resolve','../users/creator-owner'),'invalid-argument');
  await reject(center('creator-fake','dashboard'),'permission-denied');
  await reject(center('creator-reader','pin',{postIds:['creator-post']}),'permission-denied');
  await reject(center('creator-owner','pin',{postIds:Array(4).fill('creator-post')}),'invalid-argument');
  await reject(center('creator-owner','pin',{postIds:['creator-post','creator-post']}),'invalid-argument');
  await db.doc('posts/foreign-post').set({userId:'creator-other',mediaType:'image',createdAt:Timestamp.now()});
  await reject(center('creator-owner','pin',{postIds:['foreign-post']}),'permission-denied');
  await center('creator-owner','pin',{postIds:['creator-post']});
  assert.deepEqual((await center('creator-reader','welcome',{creatorId:'creator-owner'})).posts.map(p=>p.id),['creator-post']);
  const copies=await Promise.all(Array.from({length:4},()=>call('creator-reader','repost','creator-post',{enabled:true})));
  assert.equal(new Set(copies.map(p=>p.id)).size,1);
  const repostId=copies[0].id;
  assert.equal((await db.collection('post_reposts').where('postId','==','creator-post').get()).size,1);
  const repost=(await db.doc(`post_reposts/${repostId}`).get()).data();
  assert.deepEqual(Object.keys(repost).sort(),['createdAt','postId','userId']);
  assert.equal((await call('creator-other','resolve','creator-post',{repostId})).sharedBy.userId,'creator-reader');
  await reject(call('creator-other','resolve','foreign-post',{repostId}),'not-found');
  await call('creator-reader','save','creator-post',{enabled:true});
  await call('creator-reader','save','creator-post',{enabled:true});
  assert.equal((await db.collection('post_bookmarks').where('postId','==','creator-post').get()).size,1);
  const stories=await Promise.all(Array.from({length:3},()=>call('creator-reader','story','creator-post',{requestId:'same-request',note:'Buraya bakalım'})));
  assert.equal(new Set(stories.map(s=>s.id)).size,1);
  const storyId=stories[0].id, storyRef=db.doc(`stories/${storyId}`);
  const story=(await storyRef.get()).data();
  assert.equal(story.sharedPostId,'creator-post');
  assert.equal(story.imageUrl,'');
  assert.equal(story.storagePath,'');
  assert.ok(story.expiresAt.toMillis()>Date.now()+86300000);
  assert.ok((await db.doc(`users/creator-reader/story_archive/${storyId}`).get()).exists);
  await reject(call('creator-reader','story','creator-post',{requestId:'long',note:'x'.repeat(181)}),'invalid-argument');
  await call('creator-reader','view'); await call('creator-reader','view'); await call('creator-owner','view');
  await call('creator-reader','profileVisit'); await call('creator-reader','profileVisit');
  await center('creator-reader','referral',{creatorId:'creator-owner'}); await center('creator-reader','referral',{creatorId:'creator-owner'});
  let metrics=(await center('creator-owner','dashboard')).posts.find(p=>p.id==='creator-post');
  assert.equal(metrics.views,1);assert.equal(metrics.profileVisits,1);assert.equal(metrics.saves,1);assert.equal(metrics.reposts,1);assert.equal(metrics.activeStoryShares,1);
  assert.equal((await center('creator-owner','dashboard')).referrals,1);
  for(const patch of [{isPublic:false},{visibility:'private'},{accountFrozen:true},{deleted:true},{status:'draft'},{moderationStatus:'pending'},{allowReshare:false}]) {
    await original.update(patch);
    await assert.rejects(call('creator-reader','resolve'));
    await assert.rejects(call('creator-other','repost','creator-post',{enabled:true}));
    await assert.rejects(call('creator-other','story','creator-post',{requestId:'blocked',note:''}));
    const {FieldValue}=req('firebase-admin/firestore');
    await original.update(Object.fromEntries(Object.keys(patch).map(k=>[k,FieldValue.delete()])));
  }
  await db.doc('users/creator-owner/blocked/creator-reader').set({});
  await reject(call('creator-reader','resolve'),'permission-denied');
  // A third viewer cannot see a share whose actor was blocked by the original author.
  await reject(call('creator-other','resolve','creator-post',{repostId}),'permission-denied');
  await db.doc('users/creator-owner/blocked/creator-reader').delete();
  await db.doc('users/creator-reader').update({isPrivate:true});
  await reject(call('creator-other','resolve','creator-post',{repostId}),'not-found');
  await db.doc('users/creator-reader').update({isPrivate:false});
  await db.doc('users/creator-owner').update({accountStatus:'frozen'});
  await reject(call('creator-reader','resolve'),'permission-denied');
  await db.doc('users/creator-owner').update({accountStatus:'active'});
  await storyRef.update({expiresAt:Timestamp.fromMillis(Date.now()-1000)});
  await reject(call('creator-other','resolve','creator-post',{storyId}),'not-found');
  await storyRef.delete();
  assert.equal((await call('creator-reader','resolve','creator-post',{storyId})).post.id,'creator-post');
  assert.equal((await call('creator-reader','story','creator-post',{requestId:'same-request',note:''})).alreadyPublished,true);
  const plan=db.doc('travel_plans/creator-route');
  await plan.set({ownerId:'creator-owner',title:'İstanbul yürüyüşü',city:'İstanbul',isPublic:false,spotIds:['a'],spotNames:['A']});
  await reject(call('creator-reader','publishRoute','route_creator-route',{planId:'creator-route'}),'permission-denied');
  await call('creator-owner','publishRoute','route_creator-route',{planId:'creator-route'});
  assert.equal((await plan.get()).data().isPublic,true);
  await center('creator-owner','guide',{postId:'route_creator-route',note:'Gün batımında gidin.'});
  assert.equal((await call('creator-reader','resolve','route_creator-route')).post.guideNote,'Gün batımında gidin.');
  await reject(center('creator-owner','guide',{postId:'creator-post',note:'Forgery'}),'permission-denied');
  await plan.update({isPublic:false});
  await reject(call('creator-reader','resolve','route_creator-route'),'not-found');
  await original.delete();
  await reject(call('creator-reader','resolve'),'not-found');
  await call('creator-reader','repost','creator-post',{enabled:false});
  await call('creator-reader','save','creator-post',{enabled:false});
  assert.deepEqual(await call('creator-reader','state'),{reposted:false,saved:false});
  assert.deepEqual((await center('creator-reader','welcome',{creatorId:'creator-owner'})).posts,[]);
  // Exercise actual deployed rules with an authenticated client, not the Admin SDK.
  const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url'), now=Math.floor(Date.now()/1000);
  const token=uid=>`${encode({alg:'none',typ:'JWT'})}.${encode({iss:'https://securetoken.google.com/demo-tbt',aud:'demo-tbt',sub:uid,user_id:uid,iat:now,exp:now+3600,firebase:{sign_in_provider:'custom'}})}.`;
  const base=`http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/demo-tbt/databases/(default)/documents`;
  const patch=(uid,path,fields)=>fetch(`${base}/${path}?${Object.keys(fields).map(k=>`updateMask.fieldPaths=${k}`).join('&')}`,{method:'PATCH',headers:{Authorization:`Bearer ${token(uid)}`,'Content-Type':'application/json'},body:JSON.stringify({fields})});
  assert.equal((await patch('creator-reader','users/creator-reader',{isCreator:{booleanValue:true}})).status,403);
  assert.equal((await patch('creator-reader','users/creator-reader',{displayName:{stringValue:'New name'}})).status,200);
  assert.equal((await patch('creator-reader','post_reposts/forged',{userId:{stringValue:'creator-reader'},postId:{stringValue:'foreign-post'}})).status,403);
  assert.equal((await patch('creator-owner','creator_profiles/creator-owner',{pinnedPostIds:{arrayValue:{values:[]}}})).status,403);
  assert.equal((await patch('creator-reader','stories/forged',{userId:{stringValue:'creator-reader'},sharedPostId:{stringValue:'foreign-post'},expiresAt:{timestampValue:new Date(Date.now()+86400000).toISOString()}})).status,403);
  assert.equal((await patch('creator-reader',`users/creator-reader/story_archive/${storyId}`,{sharedPostId:{stringValue:'foreign-post'}})).status,403);
  const secretBookmark=await call('creator-reader','save','foreign-post',{enabled:true});
  assert.equal(secretBookmark.saved,true);
  const bookmark=(await db.collection('post_bookmarks').where('userId','==','creator-reader').get()).docs[0];
  assert.equal((await fetch(`${base}/${bookmark.ref.path}`,{headers:{Authorization:`Bearer ${token('creator-other')}`}})).status,403);
  assert.equal((await fetch(`${base}/${bookmark.ref.path}`,{headers:{Authorization:`Bearer ${token('creator-reader')}`}})).status,200);
  console.log('Creator and social publishing: reference integrity, concurrent retry, privacy, ownership, metrics and client rules passed');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>db.terminate());
