import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

import '../models/social_event.dart';
import '../services/content_engagement_service.dart';
import '../services/post_service.dart';
import '../services/social_event_service.dart';
import '../services/social_service.dart';
import '../widgets/app_video_player.dart';
import '../widgets/content_engagement_bar.dart';
import '../widgets/firebase_media_image.dart';
import '../widgets/post_media_carousel.dart';
import 'social_events_screen.dart';
import 'user_profile_screen.dart';

enum FeedMode { forYou, following }

class FeedScreen extends StatelessWidget {
  final FeedMode mode;
  final bool embedded;
  final bool includeEvents;
  const FeedScreen({super.key,this.mode=FeedMode.forYou,this.embedded=false,this.includeEvents=true});
  List<String> _strings(dynamic value)=>value is Iterable?value.map((e)=>e.toString()).where((e)=>e.isNotEmpty).toList():const<String>[];

  @override Widget build(BuildContext context){
    final currentUser=FirebaseAuth.instance.currentUser;
    final body=currentUser==null?const _SignedOutFeed():StreamBuilder<List<String>>(
      stream:SocialService.instance.followingIds(),builder:(context,followingSnapshot){
        if(followingSnapshot.connectionState==ConnectionState.waiting)return const _FeedLoading();
        final followingIds=followingSnapshot.data??<String>[];
        return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('posts').orderBy('createdAt',descending:true).limit(120).snapshots(),builder:(context,postsSnapshot){
          if(postsSnapshot.connectionState==ConnectionState.waiting)return const _FeedLoading();
          if(postsSnapshot.hasError)return Center(child:Padding(padding:const EdgeInsets.all(30),child:Text('Akış yüklenemedi.\n${postsSnapshot.error}',textAlign:TextAlign.center,style:const TextStyle(color:Colors.white70))));
          final docs=postsSnapshot.data?.docs.toList()??[];
          if(mode==FeedMode.following){docs.removeWhere((doc){final owner=(doc.data()['userId']??'').toString();return owner!=currentUser.uid&&!followingIds.contains(owner);});}else{docs.sort((a,b){final ao=(a.data()['userId']??'').toString(),bo=(b.data()['userId']??'').toString();final af=followingIds.contains(ao)?1:0,bf=followingIds.contains(bo)?1:0;if(af!=bf)return bf.compareTo(af);final at=a.data()['createdAt'],bt=b.data()['createdAt'];return at is Timestamp&&bt is Timestamp?bt.compareTo(at):0;});}
          return StreamBuilder<List<SocialEvent>>(stream:SocialEventService.instance.watchUpcoming(limit:50),builder:(context,eventsSnapshot){
            final now=DateTime.now();
            final events=(includeEvents?eventsSnapshot.data??const<SocialEvent>[]:const<SocialEvent>[]).where((event){final visible=event.visibility==EventVisibility.public||event.hostId==currentUser.uid||event.participantIds.contains(currentUser.uid)||event.allowedUserIds.contains(currentUser.uid);if(!visible)return false;if(mode==FeedMode.following&&!(followingIds.contains(event.hostId)||event.participantIds.any(followingIds.contains)))return false;return true;}).toList()..sort((a,b)=>a.startsAt.compareTo(b.startsAt));
            final tonight=events.where((event){final d=event.startsAt.toLocal();return d.year==now.year&&d.month==now.month&&d.day==now.day;}).take(6).toList();
            final items=<Widget>[];if(mode==FeedMode.forYou&&tonight.isNotEmpty)items.add(_TonightStrip(events:tonight,followingIds:followingIds));var eventIndex=0;
            for(var i=0;i<docs.length;i++){final doc=docs[i],data=doc.data();final videoUrl=(data['videoUrl']??'').toString(),mediaType=(data['mediaType']??'').toString();var mediaUrls=_strings(data['mediaUrls']),mediaPaths=_strings(data['mediaStoragePaths']);final legacyUrl=(data['imageUrl']??'').toString(),legacyPath=(data['storagePath']??'').toString();if(mediaUrls.isEmpty&&legacyUrl.isNotEmpty)mediaUrls=[legacyUrl];if(mediaPaths.isEmpty&&legacyPath.isNotEmpty)mediaPaths=[legacyPath];items.add(_FeedPostCard(postId:doc.id,userId:(data['userId']??'').toString(),userName:(data['userName']??'Topluluk üyesi').toString(),userPhotoUrl:(data['userPhotoUrl']??data['photoUrl']??'').toString(),mediaType:mediaType=='video'||videoUrl.isNotEmpty?'video':'image',imageUrl:legacyUrl,storagePath:legacyPath,mediaUrls:mediaUrls,mediaStoragePaths:mediaPaths,videoUrl:videoUrl,videoStoragePath:(data['videoStoragePath']??'').toString(),thumbnailUrl:(data['thumbnailUrl']??data['imageUrl']??'').toString(),thumbnailStoragePath:(data['thumbnailStoragePath']??data['storagePath']??'').toString(),caption:(data['caption']??'').toString(),spotName:(data['spotName']??'').toString(),createdAt:data['createdAt']));if((i+1)%4==0&&eventIndex<events.length)items.add(_EventFeedCard(event:events[eventIndex++],followingIds:followingIds));}
            while(eventIndex<events.length&&items.length<10)items.add(_EventFeedCard(event:events[eventIndex++],followingIds:followingIds));if(docs.isEmpty&&events.isEmpty)items.add(_EmptyFeed(mode:mode));
            return RefreshIndicator(onRefresh:()=>Future<void>.delayed(const Duration(milliseconds:450)),child:ListView.builder(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.only(bottom:24),itemCount:items.length,itemBuilder:(_,i)=>items[i]));
          });
        });
      });
    if(embedded)return body;return Scaffold(backgroundColor:const Color(0xFF090A0C),appBar:AppBar(backgroundColor:const Color(0xFF090A0C),title:Text(mode==FeedMode.following?'Takip':'Sana Özel')),body:body);
  }
}

class _TonightStrip extends StatelessWidget{final List<SocialEvent> events;final List<String> followingIds;const _TonightStrip({required this.events,required this.followingIds});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.fromLTRB(10,4,0,12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Padding(padding:const EdgeInsets.only(right:10,bottom:8),child:Row(children:[const Expanded(child:Text('Bu Akşam 🔥',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900))),TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SocialEventsScreen())),child:const Text('Tümünü gör'))])),SizedBox(height:154,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:events.length,separatorBuilder:(_,__)=>const SizedBox(width:9),itemBuilder:(_,i)=>SizedBox(width:230,child:_CompactEventCard(event:events[i],followingIds:followingIds))))]));}
class _CompactEventCard extends StatelessWidget{final SocialEvent event;final List<String> followingIds;const _CompactEventCard({required this.event,required this.followingIds});@override Widget build(BuildContext context){final friendCount=event.participantIds.where(followingIds.contains).length;final local=event.startsAt.toLocal(),time='${local.hour.toString().padLeft(2,'0')}:${local.minute.toString().padLeft(2,'0')}';return Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xFF15181B),borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Text(time,style:const TextStyle(fontWeight:FontWeight.w900)),const Spacer(),const Icon(Icons.groups_2_outlined,size:16,color:Colors.white54),const SizedBox(width:4),Text('${event.participantCount}',style:const TextStyle(fontSize:12,color:Colors.white70))]),const SizedBox(height:10),Text(event.title,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text(event.locationLabel.isNotEmpty?event.locationLabel:event.city,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:12,color:Colors.white54)),const Spacer(),if(friendCount>0)Text('$friendCount takip ettiğin kişi katılıyor',style:const TextStyle(fontSize:11,color:Colors.white70,fontWeight:FontWeight.w800))]));}}
class _EventFeedCard extends StatelessWidget{final SocialEvent event;final List<String> followingIds;const _EventFeedCard({required this.event,required this.followingIds});@override Widget build(BuildContext context){final uid=FirebaseAuth.instance.currentUser?.uid,joined=uid!=null&&event.participantIds.contains(uid);final local=event.startsAt.toLocal(),date='${local.day.toString().padLeft(2,'0')}.${local.month.toString().padLeft(2,'0')} • ${local.hour.toString().padLeft(2,'0')}:${local.minute.toString().padLeft(2,'0')}';Future<void> join()async{try{await SocialEventService.instance.join(event.id);}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}}return Padding(padding:const EdgeInsets.fromLTRB(14,12,14,18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(event.title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text('$date  •  ${event.locationLabel.isNotEmpty?event.locationLabel:event.city}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white60,fontSize:12)),const SizedBox(height:10),Row(children:[OutlinedButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SocialEventsScreen())),child:const Text('Etkinliği Gör')),const SizedBox(width:8),FilledButton(onPressed:joined||event.isFull?null:join,child:Text(joined?'Katıldın':event.isFull?'Dolu':'Katıl'))]),ContentEngagementBar(collection:'social_events',contentId:event.id,ownerId:event.hostId,title:event.title,sourceType:'social_event')])) ;}}
class _SignedOutFeed extends StatelessWidget{const _SignedOutFeed();@override Widget build(BuildContext context)=>const Center(child:Text('Sosyal akış için giriş yap'));}
class _EmptyFeed extends StatelessWidget{final FeedMode mode;const _EmptyFeed({required this.mode});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.all(30),child:Text(mode==FeedMode.following?'Takip akışın henüz sakin':'Henüz paylaşım yok',textAlign:TextAlign.center,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)));}

class _FeedPostCard extends StatelessWidget{
 final String postId,userId,userName,userPhotoUrl,mediaType,imageUrl,storagePath,videoUrl,videoStoragePath,thumbnailUrl,thumbnailStoragePath,caption,spotName;final List<String> mediaUrls,mediaStoragePaths;final dynamic createdAt;
 const _FeedPostCard({required this.postId,required this.userId,required this.userName,required this.userPhotoUrl,required this.mediaType,required this.imageUrl,required this.storagePath,required this.mediaUrls,required this.mediaStoragePaths,required this.videoUrl,required this.videoStoragePath,required this.thumbnailUrl,required this.thumbnailStoragePath,required this.caption,required this.spotName,required this.createdAt});
 bool get _isVideo=>mediaType=='video'&&videoUrl.isNotEmpty;
 String _timeLabel(){if(createdAt is! Timestamp)return'';final date=(createdAt as Timestamp).toDate(),diff=DateTime.now().difference(date);if(diff.inMinutes<1)return'şimdi';if(diff.inMinutes<60)return'${diff.inMinutes} dk';if(diff.inHours<24)return'${diff.inHours} sa';if(diff.inDays<7)return'${diff.inDays} gün';return'${date.day}.${date.month}.${date.year}';}
 Widget _media(BuildContext context){if(_isVideo)return AppVideoPlayer.network(url:videoUrl,autoplay:true,muted:true,loop:true,showControls:true,fit:BoxFit.cover,loading:FirebaseMediaImage(imageUrl:thumbnailUrl,storagePath:thumbnailStoragePath,width:double.infinity,height:double.infinity,fit:BoxFit.cover));return PostMediaCarousel(imageUrls:mediaUrls.isEmpty?<String>[imageUrl]:mediaUrls,storagePaths:mediaStoragePaths.isEmpty?<String>[storagePath]:mediaStoragePaths,fallbackStoragePaths:FirebaseMediaImage.postPaths(userId,postId),fit:BoxFit.cover,onDoubleTap:()=>_doubleTapLike(context));}
 Future<void> _doubleTapLike(BuildContext context)async{if(postId.trim().isEmpty)return;try{final liked=await ContentEngagementService.instance.isLiked('posts',postId).first;if(!liked)await ContentEngagementService.instance.toggleLike(collection:'posts',id:postId,ownerId:userId,title:caption.trim().isEmpty?(_isVideo?'Video paylaşımı':'Fotoğraf paylaşımı'):caption,sourceType:'post');}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}}
 Future<void> _delete(BuildContext context)async{final confirmed=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Gönderiyi sil'),content:const Text('Bu gönderi kalıcı olarak silinecek.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Sil'))]));if(confirmed==true&&context.mounted)await PostService.instance.deletePost(postId:postId,storagePath:storagePath,videoStoragePath:videoStoragePath,thumbnailStoragePath:thumbnailStoragePath);}
 @override Widget build(BuildContext context)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
   InkWell(onTap:userId.isEmpty?null:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>UserProfileScreen(userId:userId))),child:Padding(padding:const EdgeInsets.fromLTRB(12,8,6,8),child:Row(children:[SizedBox(width:36,height:36,child:ClipOval(child:FirebaseMediaImage(imageUrl:userPhotoUrl,fallbackStoragePaths:FirebaseMediaImage.avatarPaths(userId),errorWidget:const ColoredBox(color:Color(0xFF22262A),child:Icon(Icons.person_outline))))),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(userName,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:14)),if(spotName.isNotEmpty||_timeLabel().isNotEmpty)Text([if(spotName.isNotEmpty)spotName,if(_timeLabel().isNotEmpty)_timeLabel()].join(' • '),maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10.5,color:Colors.white54))])),if(FirebaseAuth.instance.currentUser?.uid==userId)PopupMenuButton<String>(onSelected:(v){if(v=='delete')_delete(context);},itemBuilder:(_)=>const[PopupMenuItem(value:'delete',child:Text('Gönderiyi sil'))],icon:const Icon(Icons.more_horiz_rounded))else const Padding(padding:EdgeInsets.all(12),child:Icon(Icons.more_horiz_rounded,size:20,color:Colors.white54))])),
   AspectRatio(aspectRatio:4/5,child:_media(context)),
   Padding(padding:const EdgeInsets.fromLTRB(8,3,8,0),child:ContentEngagementBar(collection:'posts',contentId:postId,ownerId:userId,title:caption.trim().isEmpty?(_isVideo?'Video paylaşımı':'Fotoğraf paylaşımı'):caption,sourceType:'post')),
   if(caption.trim().isNotEmpty)Padding(padding:const EdgeInsets.fromLTRB(12,0,12,10),child:Text.rich(TextSpan(children:[TextSpan(text:'$userName ',style:const TextStyle(fontWeight:FontWeight.w900)),TextSpan(text:caption,style:const TextStyle(color:Colors.white70,height:1.3))]))),
   const Divider(height:1,color:Color(0x1FFFFFFF)),const SizedBox(height:8),
 ]);
}
class _FeedLoading extends StatelessWidget{const _FeedLoading();@override Widget build(BuildContext context)=>ListView.builder(itemCount:3,itemBuilder:(_,__)=>const SizedBox(height:420,child:ColoredBox(color:Color(0xFF111315))));}
