import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../data/turkey_selection_data.dart';
import '../models/social_event.dart';
import '../services/activity_demand_service.dart';
import '../services/social_event_service.dart';
import '../theme/app_theme.dart';
import '../widgets/searchable_selection_field.dart';
import 'activity_demand_screen.dart';
import 'event_deep_link_screen.dart';
import 'event_photo_create_screen.dart';

class RadarScreen extends StatefulWidget {
  final bool embedded;
  const RadarScreen({super.key, this.embedded = false});
  @override
  State<RadarScreen> createState() => _RadarScreenState();
}

class _RadarScreenState extends State<RadarScreen> {
  static const _cityPrefKey = 'radar_city';
  static const _missionKey = 'participation_missions';
  final _cityController = TextEditingController();
  String _period = 'now';
  String _category = 'Tümü';
  String? _joiningEventId;
  Set<String> _missions = <String>{};

  static const _quickActivities = <String>['Fotoğraf','Kahve','Yürüyüş','Kamp','Koşu','Gezi'];
  static const _categories = <String>['Tümü','Sosyal','Fotoğraf','Spor','Kahve','Gezi','Doğa','Müzik'];

  @override
  void initState(){super.initState();_load();}
  @override
  void dispose(){_cityController.dispose();super.dispose();}

  Future<void> _load() async {
    try {
      final prefs=await SharedPreferences.getInstance();
      final city=prefs.getString(_cityPrefKey)?.trim()??'';
      final missions=prefs.getStringList(_missionKey)??const <String>[];
      if(!mounted)return;
      setState((){_cityController.text=city;_missions=missions.toSet();});
    } catch (_) {}
  }

  Future<void> _completeMission(String id) async {
    if(_missions.contains(id))return;
    final next={..._missions,id};
    final prefs=await SharedPreferences.getInstance();
    await prefs.setStringList(_missionKey,next.toList());
    if(mounted)setState(()=>_missions=next);
  }

  String _normalize(String v)=>v.trim().toLowerCase().replaceAll('ı','i').replaceAll('İ','i').replaceAll('ğ','g').replaceAll('ü','u').replaceAll('ş','s').replaceAll('ö','o').replaceAll('ç','c');
  bool _sameCity(String v){final c=_cityController.text.trim();return c.isEmpty||_normalize(v)==_normalize(c);}
  Future<void> _setCity(String v) async {if(mounted)setState((){});final p=await SharedPreferences.getInstance();await p.setString(_cityPrefKey,v.trim());}
  bool _eventInPeriod(SocialEvent e){final n=DateTime.now(),s=e.startsAt.toLocal();if(_period=='now')return s.isBefore(n.add(const Duration(hours:3)))&&s.isAfter(n.subtract(const Duration(minutes:30)));if(_period=='today')return s.year==n.year&&s.month==n.month&&s.day==n.day&&s.isAfter(n.subtract(const Duration(minutes:30)));return s.isBefore(n.add(const Duration(days:7)))&&s.isAfter(n.subtract(const Duration(minutes:30)));}
  bool _demandInPeriod(ActivityDemand d)=>_period=='now'?d.window=='today':_period=='today'?(d.window=='today'||d.window=='tomorrow'):true;
  bool _matchesCategory(SocialEvent e){if(_category=='Tümü')return true;return switch(_category){'Fotoğraf'=>e.type==SocialEventType.photography,'Spor'=>{SocialEventType.cycling,SocialEventType.running,SocialEventType.walking}.contains(e.type),'Kahve'=>e.type==SocialEventType.foodDrink||_normalize(e.title).contains('kahve'),'Gezi'=>e.type==SocialEventType.trip,'Doğa'=>{SocialEventType.hiking,SocialEventType.camping}.contains(e.type),'Müzik'=>{SocialEventType.concert,SocialEventType.festival,SocialEventType.dance}.contains(e.type),'Sosyal'=>{SocialEventType.social,SocialEventType.followerMeetup,SocialEventType.networking,SocialEventType.party}.contains(e.type),_=>true};}
  IconData _activityIcon(String a)=>switch(_normalize(a)){'fotograf'=>Icons.photo_camera_outlined,'kahve'=>Icons.local_cafe_outlined,'yuruyus'=>Icons.directions_walk_rounded,'kosu'=>Icons.directions_run_rounded,'kamp'=>Icons.terrain_outlined,'gezi'=>Icons.route_outlined,_=>Icons.bolt_rounded};
  IconData _eventIcon(SocialEventType t)=>switch(t){SocialEventType.photography=>Icons.photo_camera_outlined,SocialEventType.cycling=>Icons.directions_bike_rounded,SocialEventType.running=>Icons.directions_run_rounded,SocialEventType.walking=>Icons.directions_walk_rounded,SocialEventType.hiking=>Icons.terrain_outlined,SocialEventType.camping=>Icons.cabin_outlined,SocialEventType.concert=>Icons.music_note_rounded,SocialEventType.festival=>Icons.festival_outlined,SocialEventType.foodDrink=>Icons.local_cafe_outlined,SocialEventType.trip=>Icons.route_outlined,_=>Icons.groups_2_outlined};
  String _windowLabel(String w)=>w=='tomorrow'?'Yarın':w=='weekend'?'Hafta sonu':'Bugün';
  String _timeUntil(DateTime v){final d=v.toLocal().difference(DateTime.now());if(d.isNegative)return'Başladı';if(d.inMinutes<60)return'${d.inMinutes} dk sonra';if(d.inHours<24)return'${d.inHours} sa sonra';final x=v.toLocal();return'${x.day.toString().padLeft(2,'0')}.${x.month.toString().padLeft(2,'0')} • ${x.hour.toString().padLeft(2,'0')}:${x.minute.toString().padLeft(2,'0')}';}

  void _openActivity(String a,{String? city}){_completeMission('plan');Navigator.push(context,MaterialPageRoute(builder:(_)=>ActivityDemandScreen(initialActivity:a,initialCity:(city??_cityController.text).trim())));}
  void _openEvent(SocialEvent e)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>EventDeepLinkScreen(eventId:e.id)));
  Future<void> _joinNow(SocialEvent e) async {final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null){_message('Katılmak için giriş yapmalısın.');return;}if(e.hostId==uid||e.participantIds.contains(uid)){_openEvent(e);return;}if(e.isFull){_message('Bu etkinlik dolmuş.');return;}if(_joiningEventId!=null)return;setState(()=>_joiningEventId=e.id);try{await SocialEventService.instance.join(e.id);await _completeMission('join');_message('Harika! Etkinliğe katıldın 🎉');}catch(error){_message(error.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>_joiningEventId=null);}}
  void _message(String t){if(!mounted)return;ScaffoldMessenger.of(context)..hideCurrentSnackBar()..showSnackBar(SnackBar(content:Text(t)));}

  @override
  Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.background,body:SafeArea(child:StreamBuilder<List<ActivityDemand>>(stream:ActivityDemandService.instance.watchActive(),builder:(context,ds){final demands=(ds.data??const<ActivityDemand>[]).where((d)=>_sameCity(d.city)&&_demandInPeriod(d)).toList();return StreamBuilder<List<SocialEvent>>(stream:SocialEventService.instance.watchUpcoming(),builder:(context,es){final all=es.data??const<SocialEvent>[];final events=all.where((e)=>_sameCity(e.city)&&_eventInPeriod(e)&&_matchesCategory(e)).toList()..sort((a,b)=>a.startsAt.compareTo(b.startsAt));final soon=events.where((e)=>e.startsAt.isBefore(DateTime.now().add(const Duration(hours:3)))).take(8).toList();final popular=[...events]..sort((a,b)=>b.participantCount.compareTo(a.participantCount));return RefreshIndicator(color:AppColors.cyan,onRefresh:_load,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:EdgeInsets.fromLTRB(14,6,14,widget.embedded?22:92),children:[_header(),const SizedBox(height:10),_categoryStrip(),const SizedBox(height:12),_hero(events,demands),const SizedBox(height:12),_missionCard(events,demands),const SizedBox(height:18),_sectionTitle('⚡ Şimdi Çık','Önümüzdeki 3 saat içinde başlayacak planlar'),const SizedBox(height:9),_eventRail(soon),const SizedBox(height:20),_sectionTitle('🔥 Şehrin hareketli planları','Katılımı en yüksek etkinlikler'),const SizedBox(height:9),_eventRail(popular.take(8).toList()),const SizedBox(height:20),_sectionTitle('Şu an ne yapmak istiyorlar?','Aynı planı isteyen insanlarla buluş'),const SizedBox(height:9),_demandSection(demands)]));});}))),);

  Widget _header()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(!widget.embedded)...[const Row(children:[Icon(Icons.radar_rounded,color:AppColors.cyan,size:22),SizedBox(width:8),Text('Radar',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900))]),const SizedBox(height:10)],SearchableSelectionField(controller:_cityController,options:turkeyCities,labelText:'Şehir',hintText:'Şehir seç; boş bırakırsan Türkiye geneli gösterilir',prefixIcon:Icons.location_city_outlined,onChanged:_setCity,maxSuggestions:7),const SizedBox(height:8),Container(padding:const EdgeInsets.all(3),decoration:BoxDecoration(color:AppColors.surface,borderRadius:BorderRadius.circular(13),border:Border.all(color:AppColors.border)),child:Row(children:[Expanded(child:_periodButton('Şimdi','now')),Expanded(child:_periodButton('Bugün','today')),Expanded(child:_periodButton('Bu Hafta','week'))]))]);
  Widget _categoryStrip()=>SizedBox(height:37,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:_categories.length,separatorBuilder:(_,__)=>const SizedBox(width:6),itemBuilder:(context,i){final l=_categories[i],s=_category==l;return ChoiceChip(label:Text(l),selected:s,showCheckmark:false,onSelected:(_)=>setState(()=>_category=l),visualDensity:VisualDensity.compact,side:BorderSide(color:s?AppColors.cyan:AppColors.border));}));

  Widget _hero(List<SocialEvent> events,List<ActivityDemand> demands){final ids=<String>{};for(final e in events){ids.addAll(e.participantIds);}ids.addAll(demands.map((e)=>e.userId));final city=_cityController.text.trim();final people=ids.length;return Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF142129),Color(0xFF1D1529)]),borderRadius:BorderRadius.circular(20),border:Border.all(color:AppColors.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[_LiveDot(),SizedBox(width:8),Text('ŞEHRİN CANLI DURUMU',style:TextStyle(fontSize:12,fontWeight:FontWeight.w900))]),const SizedBox(height:10),Text(city.isEmpty?'Bugün ne yapmak istersin?':'$city’da bugün ne yapmak istersin?',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text('${events.length} etkinlik • $people aktif kişi',style:const TextStyle(color:Colors.white60,fontSize:12.5)),if(people>0)...[const SizedBox(height:6),Text(people==1?'Şu anda 1 kişi plan arıyor. Sen de katıl.':'Şu anda $people kişi çevrende planlara dahil oluyor.',style:const TextStyle(color:AppColors.cyan,fontSize:11,fontWeight:FontWeight.w800))],const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:(){if(events.isNotEmpty){_openEvent(events.first);}else{_openActivity('Sosyal');}},icon:const Icon(Icons.bolt_rounded),label:Text(events.isEmpty?'İlk planı başlat':'Şimdi bir plan bul')))]));}

  Widget _missionCard(List<SocialEvent> events,List<ActivityDemand> demands){final done=_missions.length.clamp(0,3);final level=done>=3?'Şehir Kaşifi':done>=1?'İlk Adım':'Yeni Gezgin';final next=done>=3?'Bugünkü görevleri tamamladın 🎉':'${3-done} görev sonra Şehir Kaşifi rozeti';return Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:AppColors.surface,borderRadius:BorderRadius.circular(18),border:Border.all(color:AppColors.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:42,height:42,decoration:BoxDecoration(color:AppColors.surfaceStrong,borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.workspace_premium_outlined,color:AppColors.cyan)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(level,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:15)),Text(next,style:const TextStyle(color:Colors.white38,fontSize:10.5))])),Text('$done/3',style:const TextStyle(color:AppColors.cyan,fontWeight:FontWeight.w900))]),const SizedBox(height:10),LinearProgressIndicator(value:done/3,minHeight:5,borderRadius:BorderRadius.circular(10)),const SizedBox(height:12),_missionRow('plan',Icons.bolt_rounded,'Bir plan başlat','Bugün ne yapmak istediğini çevrene göster',()=>_openActivity('Kahve')),_missionRow('join',Icons.groups_2_outlined,'Bir etkinliğe katıl',events.isEmpty?'Yeni bir etkinlik oluştuğunda ilk katılanlardan ol':'${events.length} plan arasından birine dahil ol',events.isEmpty?()=>_openActivity('Sosyal'):()=>_openEvent(events.first)),_missionRow('explore',Icons.explore_outlined,'Çevreni keşfet',demands.isEmpty?'Radar’da yeni planları keşfet':'${demands.length} aktif isteği incele',(){setState(()=>_period='week');_completeMission('explore');})]));}
  Widget _missionRow(String id,IconData icon,String title,String sub,VoidCallback tap){final done=_missions.contains(id);return InkWell(onTap:done?null:tap,borderRadius:BorderRadius.circular(12),child:Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(children:[Icon(done?Icons.check_circle_rounded:icon,size:20,color:done?Colors.greenAccent:Colors.white54),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(fontSize:12,fontWeight:FontWeight.w800,color:done?Colors.white38:Colors.white)),Text(sub,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white30,fontSize:9.5))])),if(!done)const Icon(Icons.chevron_right_rounded,color:Colors.white24)])));}

  Widget _periodButton(String l,String v){final s=_period==v;return Material(color:s?AppColors.surfaceStrong:Colors.transparent,borderRadius:BorderRadius.circular(10),child:InkWell(onTap:()=>setState(()=>_period=v),child:Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Text(l,textAlign:TextAlign.center,style:TextStyle(color:s?Colors.white:const Color(0x75FFFFFF),fontSize:11.5,fontWeight:s?FontWeight.w900:FontWeight.w700)))));}
  Widget _eventRail(List<SocialEvent> events){if(events.isEmpty)return Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:AppColors.surface,borderRadius:BorderRadius.circular(15),border:Border.all(color:AppColors.border)),child:const Text('Şimdilik uygun etkinlik yok. İlk planı sen başlatabilirsin.',style:TextStyle(color:Colors.white54)));return SizedBox(height:190,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:events.length,separatorBuilder:(_,__)=>const SizedBox(width:9),itemBuilder:(context,i)=>_eventCard(events[i])));}
  Widget _eventCard(SocialEvent e){final uid=FirebaseAuth.instance.currentUser?.uid;final joined=uid!=null&&(e.hostId==uid||e.participantIds.contains(uid));final loading=_joiningEventId==e.id;final remaining=e.remainingSlots.clamp(0,e.capacity);return SizedBox(width:228,child:Material(color:AppColors.surface,borderRadius:BorderRadius.circular(17),child:InkWell(onTap:()=>_openEvent(e),child:Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(borderRadius:BorderRadius.circular(17),border:Border.all(color:AppColors.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:38,height:38,decoration:BoxDecoration(color:AppColors.surfaceStrong,borderRadius:BorderRadius.circular(12)),child:Icon(_eventIcon(e.type),size:19,color:AppColors.cyan)),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_timeUntil(e.startsAt),style:const TextStyle(color:AppColors.cyan,fontSize:10.5,fontWeight:FontWeight.w900)),Text(e.city,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white38,fontSize:9.5))]))]),const SizedBox(height:10),Text(e.title,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w900)),const Spacer(),Row(children:[const Icon(Icons.groups_2_outlined,size:14,color:Colors.white38),const SizedBox(width:4),Text('${e.participantCount}/${e.capacity}',style:const TextStyle(color:Colors.white54,fontSize:10.5,fontWeight:FontWeight.w700)),if(e.participantCount>1)...[const SizedBox(width:7),Text('${e.participantCount} kişi geliyor',style:const TextStyle(color:AppColors.cyan,fontSize:9.5,fontWeight:FontWeight.w800))],if(remaining<=2&&remaining>0)...[const SizedBox(width:7),Text('Son $remaining yer',style:const TextStyle(color:Colors.orangeAccent,fontSize:9.5,fontWeight:FontWeight.w800))]]),const SizedBox(height:9),SizedBox(width:double.infinity,height:35,child:FilledButton(onPressed:loading||e.isFull?null:()=>_joinNow(e),child:loading?const SizedBox(width:15,height:15,child:CircularProgressIndicator(strokeWidth:2)):Text(joined?'Detayları Gör':e.isFull?'Dolu':'Ben de Geliyorum',style:const TextStyle(fontSize:10.5,fontWeight:FontWeight.w900))))]))))));}
  Widget _sectionTitle(String t,String s)=>_SectionHeading(title:t,subtitle:s);
  Widget _demandSection(List<ActivityDemand> demands){final grouped=<String,List<ActivityDemand>>{};for(final d in demands){grouped.putIfAbsent('${d.activity}|${d.city}|${d.window}',()=>[]).add(d);}final groups=grouped.values.toList()..sort((a,b)=>b.length.compareTo(a.length));if(groups.isEmpty)return _quickStartStrip();return SizedBox(height:104,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:groups.take(6).length,separatorBuilder:(_,__)=>const SizedBox(width:7),itemBuilder:(context,i)=>_demandCard(groups[i].first,groups[i].length)));}
  Widget _demandCard(ActivityDemand d,int count)=>SizedBox(width:155,child:Material(color:AppColors.surface,borderRadius:BorderRadius.circular(14),child:InkWell(onTap:()=>_openActivity(d.activity,city:d.city),child:Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(borderRadius:BorderRadius.circular(14),border:Border.all(color:AppColors.border)),child:Row(children:[Container(width:36,height:36,decoration:BoxDecoration(color:AppColors.surfaceStrong,borderRadius:BorderRadius.circular(11)),child:Icon(_activityIcon(d.activity),size:18,color:AppColors.cyan)),const SizedBox(width:9),Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(d.activity,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text('$count kişi • ${_windowLabel(d.window)}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white38,fontSize:9.8))]))]))))));
  Widget _quickStartStrip()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Şu an sakin. İlk hareketi sen başlat.',style:TextStyle(color:Color(0x75FFFFFF),fontSize:11.5)),const SizedBox(height:8),Wrap(spacing:7,runSpacing:7,children:_quickActivities.map((a)=>ActionChip(avatar:Icon(_activityIcon(a),size:16),label:Text(a),onPressed:()=>_openActivity(a))).toList())]);
}

class _SectionHeading extends StatelessWidget{final String title,subtitle;const _SectionHeading({required this.title,required this.subtitle});@override Widget build(BuildContext context)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900)),const SizedBox(height:1),Text(subtitle,style:const TextStyle(color:Colors.white38,fontSize:10.5))]);}
class _LiveDot extends StatefulWidget{const _LiveDot();@override State<_LiveDot> createState()=>_LiveDotState();}
class _LiveDotState extends State<_LiveDot> with SingleTickerProviderStateMixin{late final AnimationController _controller;@override void initState(){super.initState();_controller=AnimationController(vsync:this,duration:const Duration(milliseconds:1100))..repeat(reverse:true);}@override void dispose(){_controller.dispose();super.dispose();}@override Widget build(BuildContext context)=>FadeTransition(opacity:Tween<double>(begin:.35,end:1).animate(_controller),child:Container(width:7,height:7,decoration:const BoxDecoration(color:AppColors.cyan,shape:BoxShape.circle)));}
