import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:image_picker/image_picker.dart';

import '../services/story_service.dart';

class StoryPhotoEditorScreen extends StatefulWidget {
  final File photo;
  const StoryPhotoEditorScreen({super.key, required this.photo});
  @override
  State<StoryPhotoEditorScreen> createState() => _StoryPhotoEditorScreenState();
}

class _StoryPhotoEditorScreenState extends State<StoryPhotoEditorScreen> {
  final GlobalKey _canvasKey = GlobalKey();
  final TextEditingController _textController = TextEditingController();
  final FocusNode _textFocus = FocusNode();
  final ImagePicker _picker = ImagePicker();
  final List<_StoryOverlay> _overlays = <_StoryOverlay>[];
  final List<_DrawStroke> _strokes = <_DrawStroke>[];
  int? _selectedIndex;
  bool _sharing = false, _editingText = false, _emojiInput = false, _drawing = false, _movingOverlay = false, _overTrash = false, _editingBackground = false;
  Size? _sourceSize;
  _DrawStroke? _activeStroke;
  double _backgroundScale = 1, _backgroundRotation = 0, _backgroundStartScale = 1, _backgroundStartRotation = 0;
  Offset _backgroundOffset = Offset.zero;
  _FontOption _font = _fonts.first;
  Color _textColor = Colors.white, _drawColor = Colors.white;

  static const _fonts = <_FontOption>[
    _FontOption('Modern', 'sans-serif'), _FontOption('Klasik', 'serif'), _FontOption('Daktilo', 'monospace'), _FontOption('Yuvarlak', 'sans-serif-medium'), _FontOption('İnce', 'sans-serif-light'),
  ];
  static const _colors = <Color>[Colors.white, Colors.black, Color(0xFFFFE25C), Color(0xFFFF5C8A), Color(0xFF74E7FF), Color(0xFFC79AFF), Color(0xFF8EFFB5)];

  @override void initState(){super.initState();_readSourceSize();}
  Future<void> _readSourceSize() async {try{final bytes=await widget.photo.readAsBytes();final image=await decodeImageFromList(bytes);if(!mounted){image.dispose();return;}setState(()=>_sourceSize=Size(image.width.toDouble(),image.height.toDouble()));image.dispose();}catch(_){}}
  @override void dispose(){_textFocus.dispose();_textController.dispose();super.dispose();}

  void _openText({bool emoji=false}){if(_sharing)return;setState((){_editingText=true;_emojiInput=emoji;_drawing=false;_editingBackground=false;_selectedIndex=null;_textController.clear();_font=_fonts.first;_textColor=Colors.white;});WidgetsBinding.instance.addPostFrameCallback((_){if(mounted)_textFocus.requestFocus();});}
  void _cancelText(){_textFocus.unfocus();setState((){_editingText=false;_emojiInput=false;_textController.clear();});}
  void _commitText(){final value=_textController.text.trim();if(value.isEmpty)return;final size=MediaQuery.sizeOf(context);setState((){_overlays.add(_StoryOverlay.text(text:value,isEmoji:_emojiInput,fontFamily:_font.family,color:_textColor,position:Offset(size.width*.5,size.height*.43)));_selectedIndex=_overlays.length-1;_editingText=false;_emojiInput=false;_textController.clear();});_textFocus.unfocus();}
  Future<void> _addPhotos() async {if(_sharing)return;_textFocus.unfocus();try{final picked=await _picker.pickMultiImage();if(!mounted||picked.isEmpty)return;final size=MediaQuery.sizeOf(context);final remaining=math.max(0,4-_overlays.where((e)=>e.photo!=null).length);final files=picked.take(remaining).toList();if(files.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Bir Story karesine en fazla 4 ek fotoğraf koyabilirsin.')));return;}setState((){_drawing=false;_editingBackground=false;for(var i=0;i<files.length;i++){_overlays.add(_StoryOverlay.photo(photo:File(files[i].path),position:Offset(size.width*(.5+((i%2)-.5)*.18),size.height*(.42+(i~/2)*.12))));}_selectedIndex=_overlays.length-1;});}catch(error){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Fotoğraf seçilemedi: $error')));}}
  void _toggleDraw(){if(_sharing)return;_textFocus.unfocus();setState((){_drawing=!_drawing;_editingText=false;_editingBackground=false;_selectedIndex=null;});}
  void _toggleBackgroundEdit(){if(_sharing)return;_textFocus.unfocus();setState((){_editingBackground=!_editingBackground;_drawing=false;_editingText=false;_selectedIndex=null;});}
  void _undoDraw(){if(_strokes.isNotEmpty)setState(()=>_strokes.removeLast());}
  void _removeSelected(){final i=_selectedIndex;if(i==null||i<0||i>=_overlays.length)return;setState((){_overlays.removeAt(i);_selectedIndex=null;_overTrash=false;_movingOverlay=false;});}
  void _duplicateSelected(){final i=_selectedIndex;if(i==null||i<0||i>=_overlays.length)return;final item=_overlays[i];setState((){_overlays.add(item.copyWith(position:item.position+const Offset(22,22)));_selectedIndex=_overlays.length-1;});}
  void _bringSelectedForward(){final i=_selectedIndex;if(i==null||i<0||i>=_overlays.length-1)return;setState((){final item=_overlays.removeAt(i);_overlays.add(item);_selectedIndex=_overlays.length-1;});}

  double _renderPixelRatio(RenderRepaintBoundary b){final s=_sourceSize,c=b.size,d=MediaQuery.devicePixelRatioOf(context);if(s==null||s.width<=0||s.height<=0||c.width<=0||c.height<=0)return math.max(3,d);final cover=math.max(c.width/s.width,c.height/s.height);return math.max(d,1/cover);}
  Future<File> _renderStory() async {setState((){_selectedIndex=null;_editingText=false;_drawing=false;_editingBackground=false;_movingOverlay=false;_overTrash=false;});_textFocus.unfocus();await WidgetsBinding.instance.endOfFrame;if(!mounted)throw Exception('Story ekranı kapandı.');final o=_canvasKey.currentContext?.findRenderObject();if(o is! RenderRepaintBoundary)throw Exception('Story görüntüsü hazırlanamadı.');final image=await o.toImage(pixelRatio:_renderPixelRatio(o));final bytes=await image.toByteData(format:ui.ImageByteFormat.png);image.dispose();if(bytes==null)throw Exception('Story görüntüsü oluşturulamadı.');final file=File('${Directory.systemTemp.path}/tbt_story_${DateTime.now().microsecondsSinceEpoch}.png');await file.writeAsBytes(bytes.buffer.asUint8List(),flush:true);return file;}
  Future<void> _share() async {if(_sharing)return;setState(()=>_sharing=true);File? rendered;try{rendered=await _renderStory();await StoryService.instance.createStory(rendered);if(mounted)Navigator.of(context).pop(true);}catch(error){if(mounted){setState(()=>_sharing=false);ScaffoldMessenger.of(context)..hideCurrentSnackBar()..showSnackBar(SnackBar(content:Text(error.toString().replaceFirst('Exception: ',''))));}}finally{try{if(rendered!=null&&await rendered.exists())await rendered.delete();}catch(_){}}}

  @override Widget build(BuildContext context)=>PopScope(canPop:!_sharing,child:Scaffold(resizeToAvoidBottomInset:false,backgroundColor:Colors.black,body:Stack(children:[
    Positioned.fill(child:RepaintBoundary(key:_canvasKey,child:Stack(fit:StackFit.expand,children:[
      GestureDetector(behavior:HitTestBehavior.opaque,onTap:_drawing?null:()=>setState(()=>_selectedIndex=null),onScaleStart:!_editingBackground?null:(_){_backgroundStartScale=_backgroundScale;_backgroundStartRotation=_backgroundRotation;},onScaleUpdate:!_editingBackground?null:(d)=>setState((){_backgroundOffset+=d.focalPointDelta;_backgroundScale=(_backgroundStartScale*d.scale).clamp(1,6);_backgroundRotation=_backgroundStartRotation+d.rotation;}),child:Transform.translate(offset:_backgroundOffset,child:Transform.rotate(angle:_backgroundRotation,child:Transform.scale(scale:_backgroundScale,child:Image.file(widget.photo,fit:BoxFit.cover,filterQuality:FilterQuality.high,gaplessPlayback:true))))),
      CustomPaint(painter:_DrawingPainter(strokes:_strokes,activeStroke:_activeStroke)),...List.generate(_overlays.length,_buildOverlay),
    ]))),
    if(_drawing)Positioned.fill(child:GestureDetector(behavior:HitTestBehavior.translucent,onPanStart:(d)=>setState(()=>_activeStroke=_DrawStroke(color:_drawColor,width:5.5,points:[d.localPosition])),onPanUpdate:(d)=>setState(()=>_activeStroke?.points.add(d.localPosition)),onPanEnd:(_){final s=_activeStroke;setState((){if(s!=null&&s.points.length>1)_strokes.add(s);_activeStroke=null;});})),
    if(!_editingText)_buildChrome(),if(_editingText)_buildTextComposer(),if(_movingOverlay)_buildTrashTarget(),
  ])));

  Widget _buildChrome()=>Positioned.fill(child:SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(12,10,12,14),child:Stack(children:[
    Align(alignment:Alignment.topLeft,child:_CircleButton(icon:Icons.close_rounded,onTap:_sharing?null:()=>Navigator.pop(context,false))),
    if(!_drawing&&!_editingBackground)Align(alignment:Alignment.topRight,child:Column(mainAxisSize:MainAxisSize.min,children:[
      _ToolButton(icon:Icons.text_fields_rounded,label:'Yazı',onTap:()=>_openText()),const SizedBox(height:9),
      _ToolButton(icon:Icons.emoji_emotions_outlined,label:'Emoji',onTap:()=>_openText(emoji:true)),const SizedBox(height:9),
      _ToolButton(icon:Icons.add_photo_alternate_outlined,label:'Fotoğraf',onTap:_addPhotos),const SizedBox(height:9),
      _ToolButton(icon:Icons.draw_outlined,label:'Çiz',onTap:_toggleDraw),const SizedBox(height:9),
      _ToolButton(icon:Icons.crop_free_rounded,label:'Kadraj',onTap:_toggleBackgroundEdit),
    ])),
    if(_drawing)Align(alignment:Alignment.topRight,child:_ModePanel(title:'Çizim',done:_toggleDraw,child:Column(mainAxisSize:MainAxisSize.min,children:[Wrap(spacing:7,runSpacing:7,children:_colors.map((c)=>GestureDetector(onTap:()=>setState(()=>_drawColor=c),child:Container(width:26,height:26,decoration:BoxDecoration(color:c,shape:BoxShape.circle,border:Border.all(color:_drawColor==c?Colors.white:Colors.white38,width:_drawColor==c?3:1))))).toList()),const SizedBox(height:9),IconButton(onPressed:_strokes.isEmpty?null:_undoDraw,icon:const Icon(Icons.undo_rounded))]))),
    if(_editingBackground)Align(alignment:Alignment.topRight,child:_ModePanel(title:'Kadraj',done:_toggleBackgroundEdit,child:const Padding(padding:EdgeInsets.only(top:4),child:Text('Sürükle\nİki parmakla ölçekle ve döndür',textAlign:TextAlign.center,style:TextStyle(color:Colors.white70,fontSize:11,height:1.35))))),
    if(_selectedIndex!=null&&!_movingOverlay&&!_drawing&&!_editingBackground)Align(alignment:Alignment.bottomCenter,child:Padding(padding:const EdgeInsets.only(bottom:72),child:Container(padding:const EdgeInsets.symmetric(horizontal:6,vertical:4),decoration:BoxDecoration(color:const Color(0xD916181D),borderRadius:BorderRadius.circular(24),border:Border.all(color:Colors.white12)),child:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(tooltip:'Çoğalt',onPressed:_duplicateSelected,icon:const Icon(Icons.copy_rounded)),IconButton(tooltip:'Öne getir',onPressed:_bringSelectedForward,icon:const Icon(Icons.flip_to_front_rounded)),IconButton(tooltip:'Sil',onPressed:_removeSelected,icon:const Icon(Icons.delete_outline_rounded))])))),
    if(!_drawing&&!_editingBackground)Align(alignment:Alignment.bottomCenter,child:SizedBox(width:double.infinity,height:52,child:FilledButton.icon(onPressed:_sharing?null:_share,style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:Colors.black,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18))),icon:_sharing?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.arrow_upward_rounded),label:Text(_sharing?'Paylaşılıyor…':'Story’ni paylaş',style:const TextStyle(fontWeight:FontWeight.w900))))),
  ]))));

  Widget _buildTextComposer(){final keyboard=MediaQuery.viewInsetsOf(context).bottom;return Positioned.fill(child:Container(color:Colors.black45,child:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(12,8,12,0),child:Row(children:[TextButton(onPressed:_cancelText,child:const Text('Vazgeç',style:TextStyle(color:Colors.white))),const Spacer(),FilledButton(onPressed:_commitText,style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:Colors.black),child:const Text('Bitti',style:TextStyle(fontWeight:FontWeight.w900)))])),const Spacer(),Padding(padding:const EdgeInsets.symmetric(horizontal:24),child:TextField(controller:_textController,focusNode:_textFocus,autofocus:true,maxLength:180,minLines:1,maxLines:5,textAlign:TextAlign.center,keyboardType:TextInputType.multiline,style:TextStyle(fontFamily:_emojiInput?null:_font.family,color:_textColor,fontSize:_emojiInput?54:34,fontWeight:FontWeight.w900,height:1.05,shadows:const[Shadow(color:Colors.black54,blurRadius:5,offset:Offset(0,1))]),decoration:InputDecoration(border:InputBorder.none,counterText:'',hintText:_emojiInput?'Emoji seç':'Bir şey yaz…',hintStyle:const TextStyle(color:Colors.white54)))),const Spacer(),if(!_emojiInput)Padding(padding:EdgeInsets.only(bottom:keyboard>0?8:18),child:Column(mainAxisSize:MainAxisSize.min,children:[SizedBox(height:40,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:14),scrollDirection:Axis.horizontal,itemCount:_fonts.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i){final f=_fonts[i],selected=f.family==_font.family;return GestureDetector(onTap:()=>setState(()=>_font=f),child:Container(padding:const EdgeInsets.symmetric(horizontal:13),alignment:Alignment.center,decoration:BoxDecoration(color:selected?Colors.white:Colors.black54,borderRadius:BorderRadius.circular(20)),child:Text(f.label,style:TextStyle(fontFamily:f.family,color:selected?Colors.black:Colors.white,fontWeight:FontWeight.w800))));})),const SizedBox(height:8),Row(mainAxisAlignment:MainAxisAlignment.center,children:_colors.map((c)=>GestureDetector(onTap:()=>setState(()=>_textColor=c),child:Container(width:28,height:28,margin:const EdgeInsets.symmetric(horizontal:4),decoration:BoxDecoration(color:c,shape:BoxShape.circle,border:Border.all(color:_textColor==c?Colors.white:Colors.white38,width:_textColor==c?3:1))))).toList())]))]))));}

  Widget _buildTrashTarget()=>Positioned(left:0,right:0,bottom:20,child:SafeArea(top:false,child:Center(child:AnimatedContainer(duration:const Duration(milliseconds:120),width:_overTrash?68:56,height:_overTrash?68:56,decoration:BoxDecoration(color:_overTrash?Colors.redAccent:Colors.black87,shape:BoxShape.circle,border:Border.all(color:Colors.white30)),child:const Icon(Icons.delete_outline_rounded)))));
  Widget _buildOverlay(int index){final item=_overlays[index],selected=_selectedIndex==index;return Positioned(left:item.position.dx,top:item.position.dy,child:FractionalTranslation(translation:const Offset(-.5,-.5),child:GestureDetector(behavior:HitTestBehavior.translucent,onTap:_drawing||_editingBackground?null:()=>setState(()=>_selectedIndex=index),onScaleStart:_drawing||_editingBackground?null:(_){item.gestureStartScale=item.scale;item.gestureStartRotation=item.rotation;setState((){_selectedIndex=index;_movingOverlay=true;});},onScaleUpdate:_drawing||_editingBackground?null:(d){final h=MediaQuery.sizeOf(context).height;setState((){item.position+=d.focalPointDelta;item.scale=(item.gestureStartScale*d.scale).clamp(.2,7);item.rotation=item.gestureStartRotation+d.rotation;_overTrash=d.focalPoint.dy>h-125;});},onScaleEnd:_drawing||_editingBackground?null:(_){if(_overTrash){_removeSelected();}else{setState((){_movingOverlay=false;_overTrash=false;});}},child:Transform.rotate(angle:item.rotation,child:Transform.scale(scale:item.scale,child:item.photo!=null?Container(width:168,height:216,decoration:BoxDecoration(borderRadius:BorderRadius.circular(22),border:selected&&!_movingOverlay?Border.all(color:Colors.white,width:2):null,boxShadow:const[BoxShadow(color:Colors.black38,blurRadius:12)]),clipBehavior:Clip.antiAlias,child:Image.file(item.photo!,fit:BoxFit.cover,filterQuality:FilterQuality.high,gaplessPlayback:true)):Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:4),decoration:selected&&!_movingOverlay?BoxDecoration(border:Border.all(color:Colors.white70),borderRadius:BorderRadius.circular(8)):null,child:Text(item.text!,textAlign:TextAlign.center,style:item.isEmoji?const TextStyle(fontSize:58):TextStyle(color:item.color,fontFamily:item.fontFamily,fontSize:34,height:1.05,fontWeight:FontWeight.w900,shadows:const[Shadow(color:Colors.black54,blurRadius:5,offset:Offset(0,1))]))))))));}
}

class _ToolButton extends StatelessWidget{final IconData icon;final String label;final VoidCallback onTap;const _ToolButton({required this.icon,required this.label,required this.onTap});@override Widget build(BuildContext context)=>Material(color:const Color(0xB3121418),borderRadius:BorderRadius.circular(18),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(18),child:SizedBox(width:58,height:52,child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:21),const SizedBox(height:2),Text(label,style:const TextStyle(fontSize:9.5,fontWeight:FontWeight.w800))]))));}
class _ModePanel extends StatelessWidget{final String title;final VoidCallback done;final Widget child;const _ModePanel({required this.title,required this.done,required this.child});@override Widget build(BuildContext context)=>Container(width:150,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:const Color(0xD916181D),borderRadius:BorderRadius.circular(20),border:Border.all(color:Colors.white12)),child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(fontWeight:FontWeight.w900))),InkWell(onTap:done,borderRadius:BorderRadius.circular(20),child:const Padding(padding:EdgeInsets.all(5),child:Icon(Icons.check_rounded,size:20)))]),child]));}
class _StoryOverlay{final String? text;final bool isEmoji;final String? fontFamily;final Color color;final File? photo;Offset position;double scale,rotation,gestureStartScale,gestureStartRotation;_StoryOverlay._({required this.text,required this.isEmoji,required this.fontFamily,required this.color,required this.photo,required this.position,this.scale=1,this.rotation=0,this.gestureStartScale=1,this.gestureStartRotation=0});factory _StoryOverlay.text({required String text,required bool isEmoji,required String fontFamily,required Color color,required Offset position})=>_StoryOverlay._(text:text,isEmoji:isEmoji,fontFamily:fontFamily,color:color,photo:null,position:position);factory _StoryOverlay.photo({required File photo,required Offset position})=>_StoryOverlay._(text:null,isEmoji:false,fontFamily:null,color:Colors.white,photo:photo,position:position);_StoryOverlay copyWith({required Offset position})=>_StoryOverlay._(text:text,isEmoji:isEmoji,fontFamily:fontFamily,color:color,photo:photo,position:position,scale:scale,rotation:rotation);}
class _FontOption{final String label,family;const _FontOption(this.label,this.family);}
class _DrawStroke{final Color color;final double width;final List<Offset> points;_DrawStroke({required this.color,required this.width,required this.points});}
class _DrawingPainter extends CustomPainter{final List<_DrawStroke> strokes;final _DrawStroke? activeStroke;const _DrawingPainter({required this.strokes,required this.activeStroke});@override void paint(Canvas canvas,Size size){for(final stroke in <_DrawStroke>[...strokes,if(activeStroke!=null)activeStroke!]){if(stroke.points.length<2)continue;final paint=Paint()..color=stroke.color..strokeWidth=stroke.width..strokeCap=StrokeCap.round..strokeJoin=StrokeJoin.round..style=PaintingStyle.stroke..isAntiAlias=true;final path=Path()..moveTo(stroke.points.first.dx,stroke.points.first.dy);for(var i=1;i<stroke.points.length;i++)path.lineTo(stroke.points[i].dx,stroke.points[i].dy);canvas.drawPath(path,paint);}}@override bool shouldRepaint(covariant _DrawingPainter oldDelegate)=>true;}
class _CircleButton extends StatelessWidget{final IconData icon;final VoidCallback? onTap;const _CircleButton({required this.icon,required this.onTap});@override Widget build(BuildContext context)=>Material(color:Colors.black54,shape:const CircleBorder(),child:InkWell(customBorder:const CircleBorder(),onTap:onTap,child:SizedBox(width:44,height:44,child:Icon(icon,size:22,color:onTap==null?Colors.white30:Colors.white))));}
